### ISSUE TITLE
Stop sending Burden of WeenieType.Creature to everyone in CreateObject

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#1032]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

All creatures CreateObject messages currently include their burden. This was not the case for retail AC. Burden for creatures was only sent to that object, not broadcast. 

This behavior is different for other weenietypes as other objects should include burden when they have that data.

**Comment by gmriggs** [comment]
We could exclude Burden specifically for Creatures, but I think this is 1 instance of a larger design issue Property filters in AppraiseInfo (in that, there are none...)

Is there any data that determines which Properties should be sent for each object type?
