### ISSUE TITLE
Jump not seen by others

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1051]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Login any 2 Characters and stand face to face, Go thru the Emotes U,I,j and so on. They all can be seen by the other player... all but Jump. When one player jumps the other player see nothing happen.

**Comment by gmriggs** [comment]
Thanks for the bug report!

This issue has been fixed in PR 1070: https://github.com/ACEmulator/ACE/pull/1070
