### ISSUE TITLE
Inventory items reapearing in Backpack after log out/in

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1076]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

I got the latest ACE Build. deleted the old Database. Installed the latest 16PY v0.0.20. Created my Player account created my Charactor got teleported out to Holtburg with my started gear ( Academy coat, 2x oil, Starter wand, bread, Letter, book, and so on. I lifestoned and went to drop the junk on the Town Crier.
Dropped the Bread, Coat, Oils Letter and so on on the Town Crier. I kept the Tapers, Scarab, ust and Blue Gem. Ran down and grabbed a Faran Robe and went back to the LS. Logged out and back in and I got the Bread, Calling Stone (Originally given to the Society Agent) letter and book back in my backpack. I did this experiment because I had the same issue appear with the last player I was working with testing things. It put the Harvester Pincer and the heal kits as well as the ring and C note back in my pack. Even though I had done the Quest the day before, Logged out wne tot work did my daily running and so on. ( I also had left the server running after the quest) I never shut it down. It was running for like 15 Hours straight. Sorry to babble.  BTW it started with the Completed issue fix that stated something about and many more fixs. Sorry I can't remember what number it was, I think it was the one before the Lugian fix.

**Comment by Mag-nus** [comment]
To clarify.

Items you give to the town crier reappear on your character.

Can you test that items dropped on the landblock do not reappear on your character?

**Comment by Warloxx01** [comment]
If I drop them on them on the Quest giver(  if quest item ) or Town Crier they reappear in my inventory. They also reappear if dropped on the ground. Odd thing is, if dropped on the ground. When you log back in They are back in your inventory and on the ground, here is the odd part, if you Click on the item on the ground the Corresponding item in your backpack Highlights. Also if you Double click the item on the ground you can not pick it up. You have to drag it to your inventory. Then you have two of the same items.

**Comment by Mag-nus** [comment]
Can you test #1078, i think it has the fix.

**Comment by Warloxx01** [comment]
OK, WOW, If I double click the item on the ground once nothing happens, but if I double click it twice ( im using s ring) it equips it from the ground and moves the in my back pack to my finger location. But leaves the ring on the ground. if I remove the ring from my finger and then re-equip it again from my pack and then remove it again. The ring on the ground disappears.

**Comment by Mag-nus** [comment]
I think I know what the drop item bug is. I'll push a fix later.

**Comment by Mag-nus** [comment]
Ok, i just pushed what I believe is the fix.

It's possible you may have some items that have been corrupted between the drop/give. The client won't let you give or drop these items. Not even sure you can drop them on a TC. I'll have to look into how we solve this later.

Now, when you drop and give an item, the item is saved to the database. It was done this way before a recent change, but, I removed that to avoid a performance hit. They must be added back for now until I can figure out how to update just the ContainerId and WielderId properties for efficiency.
