### ISSUE TITLE
Able to drop Attune and Bonded items

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1083]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

add a Attune, Bonded item... /ci 22080
 (Imp Staff)
Attempt to drop it from your inventory. (Can't)
Equip the staff. Now drag and drop it to the ground (Have not tried to give to another character) you WILL be allowed to drop it to the ground. Another character CAN pick it up

**Comment by Mag-nus** [comment]
Should be fixed in #1197
