### ISSUE TITLE
couldn't spawn Door

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1125]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Log into game in Holtburg, move towards the Casino.

### The log given by the failure.
2018-12-09 15:46:48,237 WARN : AddWorldObjectInternal: couldn't spawn Door

### Mention any other details that might be useful.

Attached a picture of the missing door along with the error message from the server and /loc cords.

http://aka-steve.com/ACEmuHoltburgmissingdoorwarning.jpg

**Comment by LtRipley36706** [comment]
This is a @gmriggs issue, door is in database, placement system fails to spawn it correctly.

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1141
