### ISSUE TITLE
Floating NPC multiple clients

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1128]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Not sure how to reproduce as it happens off and on so far.  But what has shown the problem for me is to have two clients logged in (on same computer) and one will see the NPC just fine (standing and will face you when using) the other client will see the NPC floating as if just dropped onto the ground but just didn't finish.   Also note that both clients have the one seeing the floating NPC not in the correct position.  One player is viewing the other player in the wrong spot.  See attached video.

### The log given by the failure.

No logs created by the server

### Desired functionality.

All clients should see the NPC on the ground and should rotate to face the person using the NPC.  All clients should see the characters in the correct spots.

### Mention any other details that might be useful.

Attached video for reference - https://youtu.be/2l5Plx-3pZA

**Comment by gmriggs** [comment]
Still looking for a way to replicate the floating NPC bug

For the players being located in inconsistent locations, this should be resolved in https://github.com/ACEmulator/ACE/pull/1132. It's possible this same patch could resolve the floating NPC issue, although since I have been unable to repro the bug, I can't say for certain

**Comment by MiachofTD** [comment]
Think I found a way to recreate this issue.  Log into Holt.  Open a few NPC's.  Go into drudge hideout for a little bit killing about half the dungeon.  Exit drudge hideout via exit portal.   Run back to the NPC's you recently opened.  Some will float some may not.  Take special not the ones you didn't open to start with will not be floating.  Please see attached video.  Updated to latest version since 10:15am CST 12-22-2018.  Error log shown in video will be posted below.

https://youtu.be/x72HvoIdnBA

**Comment by MiachofTD** [comment]
2018-12-22 11:25:18,392 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3758
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454

**Comment by gmriggs** [comment]
Thanks for the update, very useful info !
