### ISSUE TITLE
Leather and Studded Leather Bracers not showing in "Slots" screen

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1129]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Use the lower Holtburg (bottom of hill side) armor/weapons NPC and buy leather and studded leather bracers.  Equip the bracers and find they do not show in the slots view and cannot be removed.  They do show in the character view and can be removed from there.

### The log given by the failure.
No log shown on the server

### Desired functionality.
Leather and studded leather bracers should show in the "Slots" view of the character for removal.  The metal bracers from the same NPC work just fine.

### Mention any other details that might be useful.
Video showing exact problem - https://youtu.be/hG3D23lY15w

**Comment by OptimShi** [comment]
This is a data related issue. 

PropertyInt.Locations (9) is set to 16 (LowerArmWear) when it should be 4096 (LowerArmArmor)

No item should have just "upper/lower arm wear" set without ChestWear also set. Similarly for underpants, which I believe should always have AdbomenWear set.
