### ISSUE TITLE
Critical: Redesign Sequence system

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#1158]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

Sequence system needs to be redesigned to be 1:1 with all of our Properties defined in enums

Overview is that each object gets a Sequences object that is keyed based on PropertyType + PropertyIndex

Each Private and Public Update for those properties would then reference this sequence in the same manner.

in ACLogView, StatType enum could be useful for the Property Type part, and we have all the properties in enums already.

**Comment by gmriggs** [comment]
Updated in https://github.com/ACEmulator/ACE/pull/1159
