### ISSUE TITLE
Creature snuck into loot

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1170]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Only has happened once but I suspect if you loot long enough it will happen.  Drudge Hideout in Holt in first largest room on corpse of recently killed Drudge.
### The log given by the failure.

No log presented but client did produce a statement saying it could not be picked up.
### Mention any other details that might be useful.

Picture showing creature on corpse of Drudge http://aka-steve.com/oddloot.png

**Comment by dgatewood** [comment]
This is corrected by PR 1171.

**Comment by MiachofTD** [comment]
As follow up, also found a Yellow Topaz Chest in the loot for a drudge in Drudge Hideout.  Did not grab a screenshot sorry and was before you corrected in PR 1171.

**Comment by gmriggs** [comment]
This has been resolved in https://github.com/ACEmulator/ACE/pull/1338
