### ISSUE TITLE
Null exception in combat, on an evade of incoming attack

### ISSUE THREAD

**Issue by kdmxp256** [ACEmulator/ACE#1172]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Enter into combat with anything.  If you evade a mobs attack, server will crash with a null exception.

### The log given by the failure.
Null check missing at line 138 of Player_Combat.cs.  Function Math.Round(), at line 149, cannot be performed on damage.Value, when damage is null

### Desired functionality.
Line 138 of Player_Combat.cs should probably be changed to "if (damage != null && target.Health.Current > 0)", instead of "if (target.Health.Current > 0)", as that whole if branch isn't needed if the attack was evaded.

**Comment by gmriggs** [comment]
This should be fixed in https://github.com/ACEmulator/ACE/pull/1168

**Comment by kdmxp256** [comment]
Confirmed fixed by commit 1168
