### ISSUE TITLE
Can't chat in @tells with admin characters

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1178]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create an admin account then character.  Have a regular player try and send an @tell to the admin character.  "That person is not available now" Message your non admin character will receive top center of game window.

### The log given by the failure.
No log given.

### Desired functionality.
Should be able to chat privately with an admin.

**Comment by gmriggs** [comment]
Patched in https://github.com/ACEmulator/ACE/pull/1177

@Mag-nus: the + name qualifiers need to be re-evaluated, maybe PlayerManager.GetOnlinePlayer() should be searching for both Player and +Player?

For a lot of the client commands, if I type /tell +Player, the client automatically strips out the + before sending the player name to the server
