### ISSUE TITLE
EmoteCategory.Refuse not performing linked action, such as a custom tell

### ISSUE THREAD

**Issue by kdmxp256** [ACEmulator/ACE#1212]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
As, one example, create a new character and try to hand the "Letter from Home" to the Society Greeter.  She should respond with "This is yours. Keep it if you like, ..." tell.  In current master, the NPC merely states "[NPC name] doesn't know what to do with this item."
Another, Samuel should have a custom response when handed the Restoring the Training Academies note from the room next to him.

### Desired functionality.
Flavor text dialog should appear when items are handed to NPCs that are coded for EmoteCategory.Refuse

**Comment by kdmxp256** [comment]
public bool HandleNPCReceiveItem() in WorldObject.cs does not account for EmoteCategory.Refuse

**Comment by gmriggs** [comment]
A PR for this issue has been posted @ https://github.com/ACEmulator/ACE/pull/1231

**Comment by kdmxp256** [comment]
Confirmed fixed
