### ISSUE TITLE
Olthoi Harvesters & Gardeners Do Not Drop Loot in Arcade North on ML

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1215]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Killing any Olthoi Harvester (11480, 11727) or Olthoi Gardener (11479. 11726) in Olthoi Arcade North in ML

### The log given by the failure.

N/A

**Comment by gmriggs** [comment]
Fixed by @dgatewood in https://github.com/ACEmulator/ACE/pull/1205

**Comment by gmriggs** [comment]
The fix from @dgatewood has been ported to https://github.com/ACEmulator/ACE/pull/1338, and is now in the master branch
