### ISSUE TITLE
Multiple Imbue / Tinker Bugs

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1227]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

- Several Observed Functioning Salvage For Tinkering Fails to Apply Magical Affects on Armor, e.g. Agate Salvage fails to apply Minor Focus on Treasure-Generated Jewelry
- The Above appears to apply for a majority of Minor Cantrip producing Salvage
- Bludgeon Rending does not appear to be working correctly - tested on a treasure-generated Wand using Shock Wave III against wisps, undead, virindi, shadows

**Comment by kdmxp256** [comment]
I don't believe that the player applied Rending bonuses have been wired up, yet.  Only the quest item variants do work.

**Comment by gmriggs** [comment]
Rends: https://github.com/ACEmulator/ACE/pull/1234
Cantrips: https://github.com/ACEmulator/ACE/pull/1254

**Comment by gmriggs** [comment]
This is now in master branch, features added in the above PRs
