### ISSUE TITLE
Treasure values change on Log out/in

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1240]
### Bug Report or Feature Request (mark with an `x`)
```

- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
While Looting in  Trothyr's Rest I found that the Loot in the chest at ( /teleloc 0x01FD0164 [50.665306 -102.731888 -5.995000] 0.015361 0.000000 0.000000 0.999882 ) Was fair cash for a low level Noob just starting out. So I grabbed it and headed back to the Lifestone. I had to log for a second  (Real life stuff) but when I logged back in and went to sell that the cash I received was far less then it should have been. So I did the looting again taking note of the values closer. Thats when I noticed the issue.
![value change](https://user-images.githubusercontent.com/38050842/50739208-ee33de80-11aa-11e9-93ac-40bcf1c9227a.jpg)

### Desired functionality.
Value should remain the same after log out and back in.

**Comment by Mag-nus** [comment]
Should be resolved by #1443
