### ISSUE TITLE
Loot item that is magical, but spell-less

### ISSUE THREAD

**Issue by DrudgeRobber** [ACEmulator/ACE#1241]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

Gotten off a drudge in the Drudge Hideout. Has the icon of a magical item, has mana, activation reqs, but no spells.

![magicalbutmagicless](https://user-images.githubusercontent.com/46425530/50740428-44f5e400-11bc-11e9-98ac-f8dbf2b809d1.jpg)

**Comment by cyberkiller6** [comment]
Can confirm, 
https://imgur.com/a/BTxmmbU

**Comment by cyberkiller6** [comment]
Adding this for more information

https://imgur.com/a/hHA7zWd

VTank] --------------Object dump--------------
[VTank] [Meta] Create count: 1
[VTank] [Meta] Create time: 4/5/2019 4:54 PM
[VTank] [Meta] Has identify data: True
[VTank] [Meta] Last ID time: 4/5/2019 4:54 PM
[VTank] [Meta] Worldfilter valid: True
[VTank] [Meta] Client valid: True
[VTank] [Meta] Apparent slot: 1
[VTank] ID: 80007CA7 (-2147451737)
[VTank] ObjectClass: WandStaffOrb
[VTank] [Memloc] Local Position: [0x0, X=0, Y=0, Z=0]
[VTank] (S) Name: Orb
[VTank] (S) FullDescription: Orb
[VTank] (B) 22: True
[VTank] (I) CreateFlags1: -1859567464
[VTank] (I) Type: 2366
[VTank] (I) Icon: 5426
[VTank] (I) Category: 32768
[VTank] (I) Behavior: 18
[VTank] (I) Value: 434
[VTank] (I) ItemUsabilityFlags: 1
[VTank] (I) UsageMask: 16
[VTank] (I) IconOutline: 1
[VTank] (I) Container: -2147451741
[VTank] (I) EquipableSlots: 16777216 (wand)
[VTank] (I) Burden: 50
[VTank] (I) HookMask: 2
[VTank] (I) Material: 60
[VTank] (I) PhysicsDataFlags: 137345
[VTank] (I) 169: 67242245
[VTank] (I) DateOfBirth: 1554497668
[VTank] (I) Workmanship: 2
[VTank] (I) GemSettingQty: 2
[VTank] (I) GemSettingType: 30
[VTank] (I) LoreRequirement: 13
[VTank] (I) MaximumMana: 1131
[VTank] (I) CurrentMana: 1131
[VTank] (I) DescriptionFormat: 7
[VTank] (I) Spellcraft: 9
[VTank] (D) SalvageWorkmanship: 2
[VTank] (D) MeleeDefenseBonus: 1
[VTank] (D) 39: 0.6
[VTank] (D) ManaRateOfChange: -0.0454545454545455
[VTank] Palette Entry 0: ID 0x000BEF, Ex Color: 000000, 0/0
