### ISSUE TITLE
Vendors do not respect "This item cannot be sold."

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#1245]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
```

### Repro steps.
@ci 305 100 // Create 100 Quarrels.
Appraise the quarrels and note the "This item cannot be sold." in the description.
Sell to an appropriate vendor.
Profit.

This item has PropertyBool.IsSellable = 0, which should prevent the vendor from purchasing it.

### Desired functionality.
I am not sure exactly the process that retail handled this, especially if you also tried to sell other items that ARE able to be sold with it.

**Comment by fartwhif** [comment]
just for reference:
1)  if an item says retained in its description then it is unable to be sold to the store, salvaged, or mana stoned
2) apply leather to an item to make it [retained](http://asheron.wikia.com/wiki/Retained), can't apply leather to quest items AFAIK

**Comment by gmriggs** [comment]
This is now fixed in https://github.com/ACEmulator/ACE/pull/1253
