### ISSUE TITLE
Tumerok archers aggro, but won't attack until you're very close

### ISSUE THREAD

**Issue by DrudgeRobber** [ACEmulator/ACE#1246]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
Tumeroks that have missile weapons (bow/crossbow) around Dryreach will aggro and equip their weapon when attacked, but refuse to fire until you're extremely close to them. Included a short video of it in action.

[noshootonlystare.zip](https://github.com/ACEmulator/ACE/files/2733968/noshootonlystare.zip)

### Repro steps.

Portal to Dryreach, attack a tumerok that has a missile weapon.

**Comment by gmriggs** [comment]
Thanks for the video :)

The mob archers currently have their range capped to something that is probably too low... I will find the same formulas the client uses for this to determine the 'max range' as shown in the appraisal window for the bow

**Comment by gmriggs** [comment]
This should be resolved in https://github.com/ACEmulator/ACE/pull/1252
