### ISSUE TITLE
ACE server 'stop-now' doesn't fully log out players

### ISSUE THREAD

**Issue by kdmxp256** [ACEmulator/ACE#1270]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Initiate a 'stop-now' process, while players are logged into the world, and they don't fully log out by themselves.  The clients must be manually shutdown before stop-now completes the ordered server shutdown.

### Desired functionality.
Fully log out the clients and terminate their sessions and connections to the server.

### Mention any other details that might be useful.
The players will be stuck in a state that the character is gone, but any equipped weapons are still visible, and the server continues to wait for the player sessions to terminate.

**Comment by Mag-nus** [comment]
I can't duplicate this.

Do you see the character logging out?

The character appearing to log out, but remain in world is how shutdowns worked in retail. This is how it currently works in ACE.

**Comment by cyberkiller6** [comment]
When I issue the shutdown command in the server console, my player 'logs' off, but weapon still shows and you can run around the world even though the server is shutdown. I don't remember it being like this in retail, I would expect it to go back to the char selection screen with a server disconnected message. 

https://imgur.com/TzhicbQ

**Comment by Mag-nus** [comment]
That is what happened at retail, when the servers went down for the final time.

After a certain amount of seconds, you'll be booted from the world into a client error screen.

**Comment by kdmxp256** [comment]
The server doesn't appear to boot the player...  Maybe I didn't wait long enough; however, the 'stop-now' command to me should boot everyone immediately.

**Comment by Mag-nus** [comment]
/stop-now is just the same as /shutdown, but instead of waiting the shutdown-interval, it pre-sets the shutdown-interval to 0 forcing the shutdown process to start immediately.

The shutdown process briefly:
forces all clients to logout
waits for all clients to log out
stops updating the world (which may happen before packets are sent to clients to return them to char selection screen)
waits for all database work to complete
returns from the main loop allowing the process to exit.

**Comment by Mag-nus** [comment]
I think this is now stale. I will close in a few days or so unless new issues are found using current master.
