### ISSUE TITLE
Movement check on spellcasting

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1282]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Start to cast a spell. 
Move a large distance.
Spell casts when wind up is done. 

### Desired functionality.
When you start to cast a spell and move a certain amount of distance before the spell finishes, instead of the spell successfully casting you should receive an error saying you have moved too far and the spell doesn't cast.

**Comment by gmriggs** [comment]
Thanks for the bug report!

Any idea what the distance threshold was for moving while casting a spell?

**Comment by gmriggs** [comment]
After discussing this more with cyberkiller and others in discord dev channels, it sounds like a radius of 6 might be a good place to start for this

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1334
