### ISSUE TITLE
Virindi Castaway NPC attacks you in Black Dominion dungeon

### ISSUE THREAD

**Issue by DrudgeRobber** [ACEmulator/ACE#1287]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
The Virindi Castaway NPC in the Black Dominion Dungeon attacks. Still functions, though.

![castaway](https://user-images.githubusercontent.com/46425530/51218288-b428b200-18f9-11e9-82df-b9e7307026ac.png)

### Repro steps.

Go into the final room of the Black Dominion dungeon and wait for him to attack you.

### Desired functionality.

A pacifist lifestyle for this poor fellow.

**Comment by kdmxp256** [comment]
Probably needs updated data

**Comment by gmriggs** [comment]
He was alerted by his friends... friend alerts need to ensure Attackable flag is set
