### ISSUE TITLE
Gear Knight model arrangement for player characters, at least, is not correct

### ISSUE THREAD

**Issue by ghost** [ACEmulator/ACE#1294]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create a Gear Knight character

### Mention any other details that might be useful.
![image](https://user-images.githubusercontent.com/22699181/51258308-8b86d380-195e-11e9-9279-7371a21055fb.png)

**Comment by fartwhif** [comment]
Ubiisoft called they said SHIP IT

**Comment by OptimShi** [comment]
Basic fix is working on local branch, so players do not literally have their butts for a head, but still doesn't display the proper body style (as it is labelled during character creation; essentially changes which textures are affected by which palette--the model shape is still the same). Will be adding a new property for players and adjusting how these "body style" player types (Gear Knights, Olthoi) are loaded with that property set.
