### ISSUE TITLE
Simulacra Infiltrators Quest - Broken XP Rewards & Partial Drops

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1298]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Handing in any of the Messaging Shards for the Quest to Diyas al-Yat will progress the Quest and giving Translations, however the XP Award of ~43M (85% lvl 90) is not disbursed for any of the below shards
Northern Infiltrator Message Shard [WCID 12143]
Southern Infiltrator Message Shard [WCID 12145]
Asteliary Crafter's Message Shard [WCID 12141]
The Northern / Southern Infiltrators nor the Crafter drop their unique palette Alumi Armor

### The log given by the failure.

N/A

### Desired functionality.

XP Recipe for Turn In's & Modify Create_List for Infiltrators 
### Mention any other details that might be useful.

http://asheron.wikia.com/wiki/Simulacra_Infiltrators

**Comment by kdmxp256** [comment]
Data driven issue.  The XP reward wasn't added until a patch in 2010.  Once the database data has been updated to that point, the XP reward will return.
