### ISSUE TITLE
Server Crashes Upon Using Magic Gems

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1299]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Upon "using" a treasure generated Black Garnet with spells on it, the server unexpectedly crashes before giving stack traces 

### The log given by the failure.

None captured

### Desired functionality.

No crashes

**Comment by gmriggs** [comment]
Duplicate of https://github.com/ACEmulator/ACE/issues/1296
