### ISSUE TITLE
Shields Appear as their Base Version when placed on Hooks

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1304]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Place Shield of the Simulacra [WCID12155] onto Wall Hook of any house, and it appears as a regular Round Shield

**Comment by gmriggs** [comment]
This is fixed in https://github.com/ACEmulator/ACE/pull/1317
