### ISSUE TITLE
Monster Corpses Not Being Generated

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1309]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Go to Black Spawn Den 56.7S, 86.0W
Kill Tuskers with War Magic
If a tusker dies and falls back into a wall, the tusker will generate no corpse.

### The log given by the failure.
AddWorldObjectInternal: couldn't spawn Corpse of Tusker Guard

### Desired functionality.
Tusker should generate a corpse in front of wall upon death.

**Comment by gmriggs** [comment]
This is fixed in https://github.com/ACEmulator/ACE/pull/1316
