### ISSUE TITLE
Lifestone tie does not give any success message

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1310]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Casting lifestone tie on a lifestone (rithwic 11.2N, 59.4E)
Spell casts
No you have successfully tied to this lifestone message appears

### Desired functionality.
After casting lifestone tie a message should appear saying that you successfully tied to the lifestone

**Comment by gmriggs** [comment]
This is fixed in https://github.com/ACEmulator/ACE/pull/1315
