### ISSUE TITLE
Fall damage does not work

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1311]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Repro steps.
Jump from a high place

### Desired functionality.
When you fall from a high place you should take fall damage.
Bludgeon protection should reduce the amount, but not eliminate the amount of fall damage.

**Comment by gmriggs** [comment]
Added in https://github.com/ACEmulator/ACE/pull/1335
