### ISSUE TITLE
Player cannot write in blank parchment/book/tome

### ISSUE THREAD

**Issue by DrudgeRobber** [ACEmulator/ACE#1337]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Purchase a parchment, book, tome, or get the lightweight tome from the Hieromancer's Armor's quest.
Attempt to write in it.

### The log given by the failure.

Received unhandled GameActionType: 0x00AC - BookAddPage

### Desired functionality.

As a great empyrean once said: *Our people once were scholars, enjoying a golden age of peace and enlightenment. I should like to see that glittering world of my childhood again.*

**Comment by gmriggs** [comment]
Added in https://github.com/ACEmulator/ACE/pull/1346
