### ISSUE TITLE
Mana Pools Don't Restore Mana

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1339]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Stand in Mana pool in meeting hall
No Mana is restored/given.

### Desired functionality.
Mana pools in meeting halls should restore Mana.
"You feel tingly as the refreshing waters wash over you, restoring 6 points of mana. "

### Mention any other details that might be useful.
http://asheron.wikia.com/wiki/Meeting_Hall

**Comment by gmriggs** [comment]
They are restoring mana, but it looks like they might be sending a text message to the player
