### ISSUE TITLE
Summon Primary Portal I is listed twice in spells book

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1343]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
/addallspells

### Desired functionality.
Summon Primary Portal I should be listed once, not twice in spell book. 

### Mention any other details that might be useful.
https://imgur.com/a/HiKTDT5

**Comment by gmriggs** [comment]
These are separate spells, Summon Primary Portal I, II, and III

Whether or not all of these should be included in /addallspells is another question..

**Comment by gmriggs** [comment]
oh i see Summon Portal I is actually listed twice in addition to this

again, these are 2 separate spells, and whether or not both should actually be learned with /addallspells would be another question

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1345
