### ISSUE TITLE
Cultist Altars don't work

### ISSUE THREAD

**Issue by DrudgeRobber** [ACEmulator/ACE#1355]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Find a Cultist Altar that spawns randomly on the Marae platea and use it.

### Desired functionality.

Should spawn the creatures as described on this page: http://acpedia.org/wiki/Cultist_Altar

**Comment by gmriggs** [comment]
Started to fix Cultist Altars in https://github.com/ACEmulator/ACE/pull/1363

When using an altar, a monster now spawns.

Todo / verify:

- If the player double clicks on the altar again, after a mob has already spawned, would it spawn another?

- After killing the monster, and using the altar a second time, the same monster always spawns again. Should this be a different monster each time, or would something happen after killing the first monster?

**Comment by DrudgeRobber** [comment]
From my memory, I never clicked it again when one was already spawned. So that's kind of a no idea.

After killing a monster it essentially goes down the list on the wikipage. As in: Use altar, kill the vapor golem, use altar, next monster spawns.

**Comment by DrudgeRobber** [comment]
Pretty close to instant, I think. If I'm remembering right there was also a delay, probably to stop you spawning multiple as you mentioned before, between when you could use it again after having used it. No message or anything, you'd hear the sound of having used it, but nothing would happen.

**Comment by gmriggs** [comment]
Okay i think this helped us solve some of the "recycling" logic that needed to be added to generators

This should now be functioning much closer to retail in https://github.com/ACEmulator/ACE/pull/1388
