### ISSUE TITLE
Gamesmaster NPC accepts stacks higher than 1

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1357]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Go to 40.9N, 33.6E
Buy a stack of 50 Monty's High-Stakes Gambling Tokens
Hand entire 50 stack to Aluvian High-Stakes Gamesmaster

### Desired functionality.
If you try to give the NPC a stack higher than 1 you get an error message, the NPC shouldn't take the entire stack. 

### Mention any other details that might be useful.
NPC took entire stack of 50, but treated it as 1 token. 
You give Aluvian High-Stakes Gamesmaster Monty's High-Stakes Gambling Token.
Aluvian High-Stakes Gamesmaster tells you, "Let's see what Dame Fortune has in store for you!"
Aluvian High-Stakes Gamesmaster gives you Large Lugian Sinew.

**Comment by cyberkiller6** [comment]
I'm not sure what the retail functionality of this was, if you when you tried to give the entire stack it only took one or it gave you an error message if you tried to hand a stack higher than 1. There was a decal plugin called Fortune hunter that automated the giving of the tokens, however I no longer have a copy of that plugin.

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1363
