### ISSUE TITLE
War Magic Against Non Player Killers

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1358]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Hit another non player kill character with war magic. 

### Desired functionality.
You should get a message saying you hit the person, but no damage was done because they are a non player killer.

**Comment by cyberkiller6** [comment]
Message is absent.

No damage was dealt.

**Comment by gmriggs** [comment]
Hmm now i also cannot get the 'long Arc shot / no collision' bug to occur with fragments...

I did indeed see a bug similar to this the first time I tested the war projectiles between NPKs, but it seems like an inconsistent repro so far

**Comment by gmriggs** [comment]
These messages have been improved in https://github.com/ACEmulator/ACE/pull/1363
