### ISSUE TITLE
Wrong messages presented when using keys

### ISSUE THREAD

**Issue by kdmxp256** [ACEmulator/ACE#1361]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Use the Pathwarden Key on the Pathwarden chest

### The log given by the failure.
"You have successfully picked the lock! It is now unlocked.
Your lockpicks have 0 uses left." is the message presented, when the key is used, which should be for lockpicks.

### Desired functionality.
Messages appropriate for key usage should be presented

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1363
