### ISSUE TITLE
Portals tied to quests print two warning messages

### ISSUE THREAD

**Issue by kdmxp256** [ACEmulator/ACE#1362]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Use a portal that has a quest completion requirement, such as the Central Courtyard portal in the Training Academy ( when using the TOD content update posted to 16-PY patches ), without having first completed the required quest.

### The log given by the failure.
Message "You must complete a quest to interact with that portal" is printed twice, first in green text, then in blue.

### Desired functionality.
Only one notification is needed per Portal usage attempts

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1363
