### ISSUE TITLE
Dispel Traps can dispel an item's built in spells that you're wearing

### ISSUE THREAD

**Issue by DrudgeRobber** [ACEmulator/ACE#1366]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

![rip](https://user-images.githubusercontent.com/46425530/51706780-73155980-1fed-11e9-9840-4f895474012a.png)

### Repro steps.

Wear an item with built in spells, such as (in my instance) the upgraded armor from http://acpedia.org/wiki/Halls_of_Knorr, and run over a dispel trap like the one in: http://acpedia.org/wiki/Lugian_Mines

### Desired functionality.

If you're wearing an item with built in spells when you're hit by a dispel trap its spells shouldn't be dispelled.

**Comment by gmriggs** [comment]
Magic trap casts Nullify All Magic Other on you and dispels: Vitae.

Fixed in https://github.com/ACEmulator/ACE/pull/1363
