### ISSUE TITLE
NPCs save to shard database

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#1367]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
```

### Repro steps.
With a clean database, create a new character.
Log in around NPCs. 
Logout. 
Note Shard database now contains the NPCs. 
Assuming the starter area is populated with NPCs, this should be Training Master, Society Greeter, Samuel and Jonathan.

### Desired functionality.
Don't save to the database.

**Comment by OptimShi** [comment]
Addendum to this, NPC equipment also saves to the shard database. e.g. "Explorer Society Robe", "Society Explorer Hat", etc

**Comment by Mag-nus** [comment]
Unfortunately, you'll have to manually delete those objects from the shard.

Can you test if this is still broken in #1370

**Comment by Mag-nus** [comment]
I believe this to be resolved.
