### ISSUE TITLE
Housing storage save - database error

### ISSUE THREAD

**Issue by gmriggs** [ACEmulator/ACE#1368]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
1. Drop an item into housing storage
2. /save-now

### The log given by the failure.
019-01-24 05:06:46,905 ERROR: SaveBiota failed with exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'NaN' in 'field list' ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'NaN' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 44

**Comment by Mag-nus** [comment]
Resolved in #1370
