### ISSUE TITLE
String Table Error in Config Settings

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1392]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Login to server
Goto settings, Character, scroll to bottom

### Mention any other details that might be useful.
https://imgur.com/a/kl4JCMQ

**Comment by gmriggs** [comment]
This is a client error from having a mismatch between your client exe and language dat file

If you use the end of retail client, and the end of retail client_local_English.dat, 'Listen to PK death messages' will appear there
