### ISSUE TITLE
Housing Issues

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1405]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```
I have noticed a couple issues when buying/using you house/cottage. I am not sure these issues affect Villas, Apartments or Mansions.

1) When purchasing a Cottage the items used to buy the property are not consumed. ( writ, special item and Cash) nor are you given the deed.

2) you can not pay your Maintenance.

3) in the storage chest the place where you can add a pack works, but if you put anything in the pack and the close the chest wait a second or two the open the chest again the pack is still there but appears empty, but if you pull the pack out (put it in one of your slot for a pack) the items are still there. 

on a side note I also have noticed that on occasion if you place things on the hooks and log out right away some items are not saved and are gone when you log back in.

**Comment by gmriggs** [comment]
All of these have been fixed in https://github.com/ACEmulator/ACE/pull/1426, except for #2, which will be coming in the next patch

**Comment by gmriggs** [comment]
All of these issues should now be resolved in https://github.com/ACEmulator/ACE/pull/1427
