### ISSUE TITLE
Landblock persistence bug

### ISSUE THREAD

**Issue by gmriggs** [ACEmulator/ACE#1444]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
/create tuskerguard
/stop-now
restart server and log in
observe: the tusker guard is there (which is correct)
/smite all
/stop-now
restart server and log in
observe: the tusker guard is still there (incorrect)

### Desired functionality.

The monster should not return alive after killing it and restarting server

**Comment by Mag-nus** [comment]
Fixed by #1447
