### ISSUE TITLE
Configurable Chat Message On Login

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1459]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.

The configurable 'Welcome' variable in config.js currently allows you to set a custom message in the welcome pop-up message that is displayed the first time a new character logs into the world. 

I propose a new configurable variable in config.js that would allow the server operator to set a message to displayed in the chat box for existing users when they login to the world. This would replace or append the current hard coded message of "Welcome to Asheron's Call powered by ACEmulator For more information on commands supported by this server, type @acehelp"

The use case for this would allow a server operator to set varying messages such as server version, scheduled downtime notices/news and any other pertinent information they would want existing characters to see in the chat box upon first logging into the world.

Another option would be to use the current 'Welcome' variable, but to change it's functionality from displaying the custom message in the welcome pop-up message to the chat box so that existing users would also see it.

Thanks for your consideration

**Comment by gmriggs** [comment]
Just for clarification:

These settings are not stored in Config.js, the runtime config default properties are stored in PropertyManager.cs

This functionality already exists in motd_string:

/modifystring motd_string hello

**Comment by gmriggs** [comment]
functionality extended in https://github.com/ACEmulator/ACE/pull/1485
