### ISSUE TITLE
Restored admin characters don't display "+" in character list

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#1470]
### Repro steps.
- Create an admin character (that is, a character with a PLUS in front of their name)
- Delete the character in the character select screen.
- Restore the character. The name will not display the "+" until you logout/log back in. (Verified with logs that the CharacterGenerationVerificationResponseEvent / 0xF643 does not send the "+" in the response)

**Comment by LtRipley36706** [comment]
Fixed #1510
