### ISSUE TITLE
character death results in character corpse appearing at the lifestone

### ISSUE THREAD

**Issue by fartwhif** [ACEmulator/ACE#1486]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro Steps

1. create a new melee character starting in Shoushi
2. pick up and equip all the leather freebie/tutorial items, quick exit the TA
3. equip the academy coat
4. upgrade and equip the starter melee weapon
5. murder "a few" mobs in the immediate newb area
6. enter Shreth Hive [32.4S, 71.0E], immediate newb area,
7. character slain while responding via starter melee weapon to an attacking drudge at the hot drop

### Mention any other details that might be useful.
* It happened once during the conditions resulting from the repro steps.
* Subsequent reproduction attempt failed with the same character.
* Reproduction attempt failed with a new character.
* Bug appears to be rare.
* It's possible that most of the repro sequence detail can be reduced away.
* Latest master branch
* Latest bleeding edge World DB has Arwic professors of Magic and facility hub spawns: https://ci.appveyor.com/api/buildjobs/g8s0xyq9q03a7rr5/artifacts/ACE-World-Database-v0.9.20-nvjslhbk.sql.zip

"Did you get express corpse delivery with your insurance package?"

**Comment by gmriggs** [comment]
https://github.com/ACEmulator/ACE/pull/1488 should ensure that CreateCorpse() is fully completed before calling TeleportOnDeath()
