### ISSUE TITLE
You can not swear to monarch after breaking from patron in same allegiance

### ISSUE THREAD

**Issue by Fortressbeast** [ACEmulator/ACE#1528]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create new character, swear to patron, break allegiance, unable to swear to new patron. In my instance it was my previous monarch. 

### The log given by the failure.
no server side log was created for this issue.

### Desired functionality.
You should be able to break from patron and then swear allegiance to the monarch of the chain.

### Mention any other details that might be useful.
The break appears to work cleanly because patron and monarch info are removed from character, and the prompt to swear allegiance does come up. However, clicking the button does not appear to do anything. No onscreen error/feedback given. This is on a fresh pull/build as of 2019-03-13, but happened in prior build from last week also

**Comment by gmriggs** [comment]
Just tested this, I think the issue might be that one of the many checks when pledging allegiance fails without returning an error message

In particular, retail had a check where the vassal must be within 4 distance of the patron. The server currently sends this error to the client:

            // check distance <= 4.0
            if (Location.DistanceTo(target.Location) > 4.0f)
            {
                Session.Network.EnqueueSend(new GameEventWeenieError(Session, WeenieError.AllegianceMaxDistanceExceeded));
                return false;
            }

However, the client doesn't seem to display this 'allegiance max distance exceeded' message

I can add some more visible error message for these cases

**Comment by gmriggs** [comment]
https://github.com/ACEmulator/ACE/pull/1530 is now in the queue

The client should now display more descriptive error messages if something happens while swearing allegiance

In addition, one of the more common and questionable cases that you experienced (guessing it was the distance > 4 check) should have the character now automatically walk over to the patron within range
