### ISSUE TITLE
When giving a player a stack of items it fails to say the number

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1534]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Give another player 50 Prismatic Tapers
Chat window says, You give Character Prismatic Taper.

It should say, 

You give Character 50 Prismatic Tapers.

**Comment by cyberkiller6** [comment]
This needs to be checked / verified

**Comment by gmriggs** [comment]
verified message from retail:

'You give <target> <stack size> <item>(s).'

(with stack size and pluralized omitted for 1)
