### ISSUE TITLE
Weakness 2 caused burden to go to 0 and can no longer pickup items

### ISSUE THREAD

**Issue by Fortressbeast** [ACEmulator/ACE#1546]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Was in Glenden Wood jails. Lich hit me with weakness 2, i could not pick up a gem from mob corpse. Waited for it to expire, but it did not fix the issue. Increased STR, didnt fix the issue. Re-log fixed the issue.

### The log given by the failure.
No server side log noted

### Desired functionality.
Spell should weaken and crease burden, not set it to 0. Player should still be able to pickup item if under max burden.

### Mention any other details that might be useful.
Not sure if it is repeatable only got hit with spell once.This was with a fresh pull/build on 20190315

**Comment by gmriggs** [comment]
I've tried every possible scenario for this, and Strength/Burden/Weakness debuff appears to be working correctly

- Glenden Wood jails doesn't appear to be a dungeon in the game (North Glenden prison?)
- If it was North Glenden prison, that dungeon is current spawning the player into a black screen, so I'm not sure how this dungeon could be it.
- The weakness spell correctly reduces the player's Strength, and any attribute cannot fall below 10.
- Nothing is setting the burden to 0. Weakness decreases strength, and burden / carrying capacity is based on strength, so weakness spell will increase burden, not set it to 0. The maximum burden is 300%
- "Player should still be able to pickup item if under max burden." The current burden of the player before picking up the item shouldn't matter. If picking up an item would put the player over 300%, then the player will not be allowed to pick that item up.

If there are any bugs related to this, clear and repeatable repro steps need to be provided. From what is listed above, everything is working correctly.

**Comment by gmriggs** [comment]
we have had another sighting of this bug (burden 0% in client display, player unable to pick anything up until relog) although this time, there was never any Weakness spells cast

still trying to figure out consistent repro steps related to this bug. as much info as possible, what the strength says in the character panel, any events that happened beforehand, or most of all any pcaps from having https://github.com/tfarley/aclog/releases installed would be of great help

**Comment by gmriggs** [comment]
Just adding some more possible info for this bug:

It might be related to the main container being full - another player has reported it happening in that case, and then once it happens, new items picked up do not go to the side containers properly

**Comment by Fortressbeast** [comment]
Was trying to figure out easily reproducible steps yesterday. Nothing concrete yet, but it seems to happen more often when using the mouse to pick up drops vs single click and "r". Often i would click too fast resulting is a triple or quad click. Other things that may be worth noting. Pack is open on side panel, almost always ID items before looting. Many times I will id other items in loot while picking up the first one. 

Fresh build as of 2019/03/29. I did not notice the main pack issue and it seemed roll over to side packs w/o issue. I will pay more attention to this today.

**Comment by Fortressbeast** [comment]
confirmed repeatable, twice so far. This issue may be caused by vtank moving Coalesed Mana from main pack to stack with items in smaller bag (starter sack in lowest slot). Will try to get it to happen again with packet capture on.
