### ISSUE TITLE
Spell appraisal and activation on items

### ISSUE THREAD

**Issue by ghost** [ACEmulator/ACE#1583]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Equip an item that was converted from LSD that has both a SpellDID (28) or ProcSpell (55) and the same spell listed in properties_spell_book but with a probablility of zero.  ACE is casting all spells in properties_spell_book on the wielder.  Additionally, spells defined as such are duplicated in the appraisal.

### The log given by the failure.
No log of failure

### Desired functionality.
Appraisal should only list unique spellIDs, if duplicated between those three properties.  This change should be applied to more than just wielded items.  Properties_spell_book listed spells with a probability value of zero should not be cast on the wielder.  Even though possibly improper, as examples from PY16 data don't have spells from property DID 28 also listed in properties_spell_book,  making this change would increase compatibility with LSD created weenie files.

### Mention any other details that might be useful.
Royal Runed Slashing Baton (https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/51b6d017e931ff4f03558cca7929a7a3a34b29cc/Database/Patches/2005-07-ThroneOfDestiny/9%20WeenieDefaults/Caster/33206%20Royal%20Runed%20Slashing%20Baton.sql) from Patches release 0.30 or earlier for an example of SpellDID duplication
Royal Runed Flamberge (https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/51b6d017e931ff4f03558cca7929a7a3a34b29cc/Database/Patches/2005-07-ThroneOfDestiny/9%20WeenieDefaults/MeleeWeapon/33212%20Royal%20Runed%20Flamberge.sql) from Patches release 0.30 or earlier for an example of ProcDID duplication

**Comment by gmriggs** [comment]
I can look at preventing this at the code level, but technically this is a data bug.

In the original PY16 data, if an item had a SpellDID, it did not appear in the spellbook. This data should be fixed ideally.

**Comment by Theran578** [comment]
I would agree that the ideal fix would be to change the data; however, until those items are found, reported, and fixed, they cause bugged spell casts for players.  It might help the process along if a debug warning message was added that posts a message to the server console and in the log.  That was how I found a good portion of the loot gen weenies that were missing their TsysMutationData.

**Comment by gmriggs** [comment]
Yep, that can definitely be added
