### ISSUE TITLE
Using the cloak on command still shows player's dot on radar

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1586]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create an admin character
Use the admin command, /cloak on
Other players can't see your player model, but they will still see your dot on their radar.

### Desired functionality.
/cloak on should hide the player model and hide the radar dot so a regular player cannot tell the cloaked admin is there. 

### Mention any other details that might be useful.

"cloak needs to delete the cloaked admin and stop sending updates as well probably (remove that player from the visibility list of others)"

**Comment by cyberkiller6** [comment]
When using /cloak on and then /cloak off you are still invisible to other players also.

**Comment by LtRipley36706** [comment]
fixed
