### ISSUE TITLE
Stacking items causes permanent hour glass

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1608]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create a character in holtburg
Go to archmage
Buy hematites until pack is full
Select hematite and press F repeatedly to stack it
Permanent hourglass occurs

### Desired functionality.
No permanent hourglass from stacking items

**Comment by Mag-nus** [comment]
Can you try this without plugins?

I am unable to duplicate

**Comment by cyberkiller6** [comment]
Can't repro with decal off.

Seems to only happen with decal running

**Comment by gmriggs** [comment]
Have been trying to repro this one for many months, so far have not been able to repro it locally or on CE

I think it might have something to do with packet reordering, and the client receive packets in a different order in which the server sent them

Any chance of getting a pcap of this bug in action?
