### ISSUE TITLE
Configurable Option For Character Save Time

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1621]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.
Would like to request a configurable option for character save time. Allow server operators to specify/change the default 5 minute character save time to x amount of minutes they choose.

**Comment by dgarson** [comment]
I took a stab at this due to it being inactive for a long time.

**Comment by dgarson** [comment]
I think this ticket can be closed.

**Comment by Mag-nus** [comment]
I'm closing this.

Much of ACE is balanced around certain conditions, such as the current 5 minute defined save interval. Misunderstanding the gravity of the property, or accidentally changing it, could result in drastic performance and/or data corruption issues.

If such an adjustment is required, it should likely be done by the server operator in their own local code repo.
