### ISSUE TITLE
Unable to move to object error when trying to sell item to vendor

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1639]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Buy hematite from archmage in holtburg
Try to sell back the hematite
Get an unexpected Unable to move to object error in yellow at top of screen

Decal Off

### Desired functionality.
Should either be able to sell the item or get an error message saying the vendor doesn't purchase that item. 

### Mention any other details that might be useful.
Video demonstration
https://megaupload.nz/wfz2p5Y4md/Asheron_s_Call_2019-04-03_16-14-37_mp4

**Comment by Mag-nus** [comment]
PropertyBool.IsSellable for the item is set to false, not null, so this poses a problem. Will need to investigate

**Comment by Mag-nus** [comment]
Per Scribble, pcaps indicate these were not sellable in retail. Looks like we need to fix the error message then.
