### ISSUE TITLE
Give Characters a set of positions

### ISSUE THREAD

**Issue by Mogwai-AC** [ACEmulator/ACE#166]
Make an enum for the following positions types:
* Physical Location
* Lifestone Used
* Lifestone Tied
* Portal Recall
* Primary Portal Recall
* Secondary Portal Recall
* Allegiance Hometown (This should only apply to monarchs)
* Mansion Recall

Notes / Requirements
* The character database model will need to change so that players have a set of positions rather than a single position
* The character object will have 1 new property for each of the recall locations in the enumeration, where Allegiance Hometown will attempt to find the monarch's Allegiance Hometown.  If you can't do this yet, just slap a // TODO and return null.
* Each of these positions should save to the database whenever changed.
* Hook up the /lifestone and /ls commands to go to the Lifestone position.

**Comment by ogmage78** [comment]
This is inprogress
