### ISSUE TITLE
StopConditionsMax console output

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#1664]
I'm seeing a lot of lines like the following:
Sturdy Steel Chest.StopConditionsMax(): CurrentCreate(4) > MaxCreate(3)

It's my understanding that these are issues caused by content.

How can we better log these issues in a better manner that gives us the necessary information to the content developers to resolve the issue.

See WorldObject_Generator.cs, line 294 and 312

**Comment by gmriggs** [comment]
maybe put the wcid of the generator
