### ISSUE TITLE
AddWorldObjectInternal: couldn't spawn X

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#1665]
In Landblock.cs, line 564 in function AddWorldObjectInternal(),

If the item fails to add, a WARN message is logged.

I think we should change this to DEBUG for landscape/scatter placements and leave WARN for all else.

Is this something that would be possible?

Can we detect if the wo is from a scatter generator by accessing the wo directly, or should we include an argument to the function to indicate adds as a result of a scatter generator?

**Comment by gmriggs** [comment]
yep debug is fine with me
