### ISSUE TITLE
Blackmire quests won't successfully complete

### ISSUE THREAD

**Issue by Theran578** [ACEmulator/ACE#1737]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
http://acpedia.org/wiki/Blackmire
Quests do not function correctly.

### The log given by the failure.
No log generated

### Mention any other details that might be useful.
Fellowship driven emotes and portal spells need code to be completed for quests to work successfully.

**Comment by LtRipley36706** [comment]
portal part fixed in #1728
