### ISSUE TITLE
Cannot apply lower reduction kit to leggings

### ISSUE THREAD

**Issue by dgarson** [ACEmulator/ACE#1885]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Repro steps.
Attempt to apply an Armor Lower Reduction Kit to any leg armor, it will say that it cannot be applied.

### The log given by the failure.
N/A

### Desired functionality.
The leg armor should be reduced so that it only covers greaves.

### Mention any other details that might be useful.
The code all lives in Tailoring.cs and is identical to the code used for upper arm reduction.

**Comment by mattfeldman** [comment]
This was fixed with PR #1886
