### ISSUE TITLE
Thrown weapon vs dual wielding

### ISSUE THREAD

**Issue by Theran578** [ACEmulator/ACE#1921]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Equipping a thrown weapon, such as wcid 304, while dual wielding, doesn't remove the second weapon

### The log given by the failure.
No logs given by the failure

### Desired functionality.
When a thrown weapon is equipped, the secondary weapon should be removed, also.

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/2044
