### ISSUE TITLE
Old Chest for Healing Machine Hook in Ruschk Iceberg missing.

### ISSUE THREAD

**Issue by NovImber** [ACEmulator/ACE#1941]
```
- [X] bug report -> please search issues before submitting (Done)
- [ ] feature request
```

### Repro steps.
Enter Ruschk Iceberg at 96.3N, 60.0W
Proceed through dungeon.
The door that requires the Ruschk Iceberk Key will open without using it, but you may use the key. I have repeated these steps in both cases.
At the end of the dungeon, the Old Chest that should be there is missing.

### The log given by the failure.
Given the simplicity and easy duplication of this bug, I did not think a log or packet capture was necessary. I would be happy to provide one on request. 

### Desired functionality.
There should be an Old Chest near the exit portal. 

### Mention any other details that might be useful.
This was the only item in the quest line with this issue. All those before and after seem to work as intended. 
This item is required for the Fiun Healing Machine quest: https://asheron.fandom.com/wiki/Fiun_Healing_Machine_Quest
EDIT: I have included a screenshot and described the behavior using Vsense further below.

**Comment by Theran578** [comment]
Old Chest is present in this dungeon: 0x02DE015A [208.458954 -97.311821 -35.994999] 0.512562 0.000000 0.000000 -0.858650

![image](https://user-images.githubusercontent.com/49040547/58456707-bab20c00-80d9-11e9-8aff-34d562afe662.png)

**Comment by NovImber** [comment]
Hi Theran578, thank you very much for looking into it. Unfortunately I don't quite have your luck.

Got some more info with Vsense:
I thought to Vsense and it seems to detect it near the large room towards the end of the dungeon. I can click the name in Vsense and its name appears in the bottom for a second before it goes away. This is similar to when I select a dye plant on the overworld that is out of range, but in this case it does not have the white indicator showing where the item is. If I press the 'use' key when it is selected this way, my character starts walking forward whichever way they are facing and the message that the chest is locked appears immediately. The character continues walking forward until interrupted. 
It's like the chest is everywhere and nowhere. 

I experience this issue with multiple characters on the Coldeve server. 

![image](https://user-images.githubusercontent.com/51051520/58636421-8cf2e000-82f0-11e9-88fb-745a7e37a3e3.png)

**Comment by NovImber** [comment]
I noticed a lot of mention of Generators in recent patch notes. I was hopeful but it didn't seem to fix the issue.

**Comment by LtRipley36706** [comment]
Should be fixed in next db release

**Comment by LtRipley36706** [comment]
@NovImber Latest DB release should have corrected this issue, let us know if not
