### ISSUE TITLE
Wield requirement checks aren't being enforced for equipping ammunition

### ISSUE THREAD

**Issue by Theran578** [ACEmulator/ACE#1986]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Player is able to equip Deadly Prismatic Arrow, /ci 43951, without satisfying the three wield requirement checks

### The log given by the failure.
No log of failure

### Desired functionality.
To match retail, wield requirement checks should probably be enforced for ammunition equipping

**Comment by gmriggs** [comment]
i am checking out the bug report where wielding ammo isn't performing the wield requirement checks
/ci arrowdeadlyfire
i create a deadly fire arrow in my inventory... not sure what the exact wield requirements are for it, but i'm doing it on my char that isn't an archer
when i try to wield it, i get the transient error 'The Deadly Fire Arrow can't be wielded'
if it do it on my archer, he is able to wield it
trying the exact repro steps in the bug report
/ci 43951
even on my archer, i don't satify the specialized fletching requirement
and it doesn't let me wield the deadly prismatic arrow
i then specialize fletching, and now meet all the requirements
and now i am able to wield the deadly prismatic arrow

can't repro this issue so far?

**Comment by gmriggs** [comment]
i see the bug maybe
it's only performing the first wield requirement check
it might not be checking all of them

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1987
