### ISSUE TITLE
Server should have a way to apply DB migrations

### ISSUE THREAD

**Issue by zbuc** [ACEmulator/ACE#20]
The server should have a way to track which DB migrations it has applied, and automatically apply missing ones in the correct order.

@Mag-nus suggested a naming convention of `YYYY_MM_DD_tablename.sql`. This would work, but would make dealing with pull requests and merges annoying, if multiple came in one day.

I would suggest a naming scheme more along the lines of `$patchNumber + '_' + $YYYY_MM_DD + '_' + $descriptiveFeatureName`, for example `01_2017_02_03_add_monster_information.sql` and not limiting them to any particular tables.

Picking the second naming system will make dealing with pull requests easier and help developers understand what updates are for. Additionally, the leading number provides a good way of tracking our schema revision.

**Comment by zbuc** [comment]
I suggest a reasonable first version of this might look like:

1) an update to the core .sql file and `Config.json` to add a new `ace_global` database with a table `schema_revisions` tracking database schema versions

The columns might be something like:

`id int(auto increment), schema_name varchar, schema_version int`

also insert initial values into the `schema_revisions` table to set the current `schema_version` at 0 on all databases (`ace_auth`, `ace_character`, `ace_world`).

2) add a task that runs during server startup that uses the database names from `Config.json` and compares the .sql files found on the filesystem against the results from `ace_global.schema_revisions` and runs the new ones, and updates the database.

**Comment by zbuc** [comment]
Almost done with this...

**Comment by Mogwai-AC** [comment]
this was recently done with a powershell script that was merged.  if you're ok with using that, please close the issue.

**Comment by zbuc** [comment]
The script can only recreate the initial database table state completely so it won't be useful for server operators.

If it were extended with a second script solely for running upgrades that could keep track of the currently run database upgrades somewhere, for example in a flat-file in a temporary directory, so they wouldn't be run again that would be useful.

**Comment by Mogwai-AC** [comment]
The scripts would need to be altered to be re-run safe.  MySQL's support for this is spotty, but it could be done.

**Comment by zbuc** [comment]
For a solution that doesn't require migration authors to worry about that, do something similar to the pull request I created where it tracks the database migrations that have run and only runs them once, in sequential order. 

That is relatively standard for database-backed applications.

You will also run into difficulty with migrations where they are interdependent, i.e. one migration needs to run before another one can be run, because it creates or alters tables used by the other migration. 

My pull request took all this into account. 

With your PowerShell solution you could probably track the migrations that have run in a text file or registry key.

**Comment by Mag-nus** [comment]
This is pretty stale and we've changed some of the database script since.

If this is still an issue we should look into, please open up a new ticket pertaining to the current code base.
