### ISSUE TITLE
Armor/Item Sets throwing Errors

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#2007]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Load the Empyrean Ring Set and the Prismatic Shadow Armor Set into your DB. the /ci any of the items ( /ci 34706 = Red Empyrean Ring or /ci 49921 = Prismatic Shadow Helm 

WARNING: Once equipped they CAN NOT BE REMOVED. 

### The log given by the failure.
Just uploading the whole thing.
[Item-Armor-Error text.zip](https://github.com/ACEmulator/ACE/files/3294273/Item-Armor-Error.text.zip)

### Mention any other details that might be useful.
it appears that it only is the "sets" that have the trouble.

**Comment by Theran578** [comment]
To my knowledge, it isn't really advised to load PCAP-Export files into the database, as is, especially for items that are way in future patches than that of where content is currently at.  A lot of PCAP-Export items may not be fully formed and may not work correctly, even setting aside new properties that may not be supported in ones emulator flavor of choice.  Many weenies have a lot more to them than were captured via PCAP'ing.  Personally, I would not call this a bug per se.

**Comment by Mag-nus** [comment]
Item sets seem to cast their spells fine for me, using retail pcapped and exported items. Perhaps your items have incomplete data?

A bug I did notice is this.

You equip item 1: Defenders Set. You meet the activation requirements.
You equip item 2: Defenders Set. You DO NOT meet the activation requirements.
You will not receive the bonus spells for having 2 of the set items equipped.

However:

You equip item 1: Defenders Set. You DO NOT meet the activation requirements.
You equip item 2: Defenders Set. You meet the activation requirements.
You WILL receive the bonus spells for having 2 of the set items equipped.
