### ISSUE TITLE
Potions filling up the wrong resource pool.

### ISSUE THREAD

**Issue by Roteleks** [ACEmulator/ACE#2015]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
- Stamina potions display that it is restoring stamina but it erroneously refills the mana pool.
- Health potions display that it is restoring health but it erroneously refills the stamina pool.
- Mana potions just don't work at all. The message displayed reads: '_Mana Elixir (8002470E) contains invalid vital Mana_'

### The log given by the failure.
The server does not report any errors or warnings.

### Desired functionality.
Potions should refill the appropriate resource type.

### Mention any other details that might be useful.
This was tested with the Stamina Tincture, Stamina Brew, Health Elixir, and Mana Elixir. I've restarted ACEmulator, and the Windows 10 VM that runs it, neither made any difference.

**Comment by gmriggs** [comment]
fixed in https://github.com/ACEmulator/ACE/pull/2011/commits/1f5bf46c4b2d669fc8f7285f2db743ee26b07bce

**Comment by Roteleks** [comment]
Thanks for the quick response! I'll just sit tight and wait for the merge so I can pull the fix.
