### ISSUE TITLE
Character rotation

### ISSUE THREAD

**Issue by ogmage78** [ACEmulator/ACE#209]
I have not had a chance to look into it, but either on the save or the load, we are not saving or loading the character rotation (facing direction) correctly.   You log out facing one way, you log back in in the same spot rotated 90 degrees.

**Comment by fantoms** [comment]
After testing a few times, I believe that your commit b52abcd is the culprit. When I revert this change, rotations are restored.

**Comment by fantoms** [comment]
PR #214 seems to also fix the issue for me.

**Comment by LtRipley36706** [comment]
agreed, this issue seems resolved. Closing for now.
