### ISSUE TITLE
Teleporting players are not removed from client if player teleports to another dungeon

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#231]

**Comment by LtRipley36706** [comment]
To reproduce:
Connect two or more clients to same server
teleport both to same location outdoors
teleport one away to another outdoor location
client disappears
return client to original outdoor location
@mp both clients
from mp, teleport to another dungeon
@teleloc 013A01E2 21.68 -50.02 6.11 -0.70 0.00 0.00 -0.71 (for example)
the client that is supposed to portal away is left on the remaining client screen.

**Comment by spazmodica** [comment]
Resolved with https://github.com/ACEmulator/ACE/pull/596

**Comment by LtRipley36706** [comment]
Fixed in #675 in FakePhysics..
