### ISSUE TITLE
Issues with second client

### ISSUE THREAD

**Issue by ogmage78** [ACEmulator/ACE#233]
When more than one person is logged on to the server, the second person never comes out of portal space until they move.   This may be an incorrect setting of contact.   Also under the same use case - if 2 clients are logged in, from the perspective of each client - the other jumps and briefly does the falling animation with every movement.   In looking at live world pcaps, it looks like almost all movements have the contact flag set to true.   It looks to be that way in ours.   I am putting this here so it is documented - if anyone has time to look for this great - if not, I will try to see if I can debug it.

**Comment by LtRipley36706** [comment]
I think this is a symptom of a lack of broadcasting of several things related to movement.. My guess it to resolve it queues will need to be built out for MoveToState and likely a change for UpdatePosition...

**Comment by LtRipley36706** [comment]
AutonomousPosition might be another event needing a queue as well to help smooth things out
