### ISSUE TITLE
Criticals don't work with Martyr's hecatomb like they did in retail.

### ISSUE THREAD

**Issue by jspashett** [ACEmulator/ACE#2507]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Have 3 wands:
plain wand
Critical strike wand made with opal
Biting strike quest wand (such as Branith's staff)

Tested on Coldeve, against target drudges in Yanshi
1. Use Martyr's Hecatomb (VII in this case) repeatedly
2. Count the number of critical strikes made.
3. Observe that 
(a) normal wands never give critical hits, but should give 5% like retail
(b) critical strike don't give > 5% - 50% critical hits
(c) biting strike does seem to work 33% critical from Branith's quest wand

Please see example below
### The log given by the failure.

Here is the summary of the results:

refs:
https://asheron.fandom.com/wiki/Combat

Critical hits should happen at least 5% of the time for magic
------------------------------------------------------------
jason@firestorm MSYS /c/temp
$ grep -i hecatomb starter_wand.log  | wc -l
37

jason@firestorm MSYS /c/temp
$ grep -i hecatomb starter_wand.log  | grep -i crit | wc -l
0

Critial hits should happen higher than 5% of the time up to a 50%? based on skill
-----------------------------------------------------------------------------------------------
$ grep -i hecatomb critical_strike.log  | wc -l
34

jason@firestorm MSYS /c/temp
$ grep -i hecatomb critical_strike.log  | grep -i critical | wc -l
0

Biting strike is probably working at 8 / 33 = 33%
-------------------------------------------------------------------

$ grep -i hecatomb biting_strike.log  | wc -l
33

jason@firestorm MSYS /c/temp
$ grep -i hecatomb biting_strike.log  | grep -i critical | wc -l
8

### Desired functionality.

Work as in retail, with the magic criticals all working the same for each school

### Mention any other details that might be useful.

I have the raw logs if interested

**Comment by jspashett** [comment]
I can look into this bug, but would like a clue if it's code or spell tables. Also will try fish out some old forum posts to verify the behavior.

**Comment by ziang4891** [comment]
This point has been gone over and over.  Yes, they do crits just like war projectiles.  The lifebolts are not treated any differently than the war projectiles.  You cannot use the wiki as the sole source of authority.  Also, you cannot use statistical data to argue probabilites.
There is only a 2% base chance for a critical strike with projectile magic, which is backed up by an announcement letter from Turbine.  http://acpedia.org/wiki/Announcements_-_2002/08_-_Atonement#Letter_to_the_Players  The five percent minimum only comes into play, when using critical strike mod'ed casters.  In that case, it scales from 5% to 50%

**Comment by jspashett** [comment]
Ok thanks. I will try it with more casts. It was surprising that branith was doing ~33% but the tinkered wand doing 0 out of 33 vs 8/33 for Branith

"Also, you cannot use statistical data to argue probabilities" The more you do the closer to the real answer it will get, so I think it should give a good indication. If it's still 0 at 200 then there could be a problem. However I am probably missing something, my life skill was only 375

Aa regards the wiki I only mentioned it as a guide since I have no other information at the moment, and was told by a lot of people that it wasn't supposed to work at all.

I appreciate the reply, I will close the bug and test it with more casts. I'll have a look to see what the formula is too. Thank you.

**Comment by jspashett** [comment]
I have tested this on a local test server with life magic at 1033 and a Critical strike wand. Crits were low at about 2%

Branith's staff crits about 33% of the time which is an easily noticeable difference.

I can supply logs if interested, or can look into the reason if someone can hint me if it is a code or sql data issue.

**Comment by ziang4891** [comment]
That is not how probabilities work...  You cannot take statistical data and say the model is broken.

**Comment by ziang4891** [comment]
Just because you received 2% of your sample set as critical strikes doesn't mean the the probability of the crit is 2%.  It only means that 2% of the casts you made happened to crit.

**Comment by jspashett** [comment]
What you say doesn't make sense, The sample set should always reflect the probability. Here are the results, clearly here Life magic does not work with Critical stike - war magic does. it's black and white,

Life Magic @ 466 base
---------------------

$ grep -i heca life.log  | wc -l
53

jason@firestorm MSYS /c/temp
$ grep -i heca life.log  | grep -i crit | wc -l
3


3/53 = 5.6%


War Magic @ 466 base
--------------------

$ grep -i acid war.log | wc -l
53

jason@firestorm MSYS /c/temp
$ grep -i acid war.log | grep -i crit |wc -l
22


22/53 = 41.5%

**Comment by ziang4891** [comment]
Unless you can come up with a sample set that is infinitely large, your sampling only shows what happened for your particular sample set, not the probability for a crit to occur is.

**Comment by gmriggs** [comment]
Clearing out this conversation history, because there is a lot of misinformation in here

**Comment by gmriggs** [comment]
@jspashett can you provide any examples from retail that Martyr's Hecatomb had a chance to crit? Any lines from the retail pcaps, or any videos from retail would be fine

**Comment by jspashett** [comment]
Well, I probably can't provide retail evidence just now, However seems like the debate is currently whether my tests are valid. 

The chance of having only 5% crits for a CS weapon that should do about 40% over 52 casts is infinity small (and I've posed this twice now)

52 coin tosses all landing the same (at 50% probability) is as follows:

0.5 ^ 52 = 2.2204460492503130808472633361816e-16‬
^ = power
That would be 0.00000000000000002204 or so %

I hope this illustrates my point. My results may not be totally accurate, but they are improbable if you say this is working. 

I can go and try and find some turbine documentations on this if desired. I am currently looking at the code to see why this may happen. it seems clear was does a different thing than life magic does, every single time, by a huge margin.

**Comment by gmriggs** [comment]
Ad-hoc testing of this on ACE is currently unneeded. The code is open source and everything about how it currently works is available to anyone.

There is currently no code for life projectiles to crit, because there have been no examples provided yet of a life projectile critting in retail.

**Comment by jspashett** [comment]
@gmriggs Life magic projectiles do crit though on ACE right now, it's just that the CS property doesn't work. If the question is whether they should or not, then I can go away and try and find that information. I did play a Martyr mage for several years using a CS wand, so I know they used to crit the same as war, but I'll try and find some authoritative information on the subject.

**Comment by gmriggs** [comment]
Ok you are indeed correct about that -- the relevant code is in SpellProjectile.cs on line 397:

```
                // could life magic projectiles crit?
                // if so, did they use the same 1.5x formula as war magic, instead of 2.0x?
                if (criticalHit)
                    damageBonus = lifeMagicDamage * 0.5f * GetWeaponCritDamageMod(sourceCreature, attackSkill, target);
```

And the part before that, which should be working the same for all spell projectiles (life / war / void bolts):

```
            // critical hit
            var critical = GetWeaponMagicCritFrequency(sourceCreature, attackSkill, target);
            if (ThreadSafeRandom.Next(0.0f, 1.0f) < critical)
            {
                if (targetPlayer != null && targetPlayer.AugmentationCriticalDefense > 0)
                {
                    var criticalDefenseMod = sourcePlayer != null ? 0.05f : 0.25f;
                    var criticalDefenseChance = targetPlayer.AugmentationCriticalDefense * criticalDefenseMod;

                    if (criticalDefenseChance > ThreadSafeRandom.Next(0.0f, 1.0f))
                        critDefended = true;
                }

                if (!critDefended)
                    criticalHit = true;
            }
```

I can look into why any existing code is currently not functioning to the intention of how its currently written

**Comment by gmriggs** [comment]
Your spells are most likely critting. They just aren't displaying the crit/sneak attack/overpower messages.

```
                var critMsg = critical ? "Critical hit! " : "";
                var sneakMsg = sneakAttackMod > 1.0f ? "Sneak Attack! " : "";
                var overpowerMsg = overpower ? "Overpower! " : "";
				
				var attackerMsg = $"{critMsg}{overpowerMsg}{sneakMsg}You {verb} {target.Name} for {amount} points with {Spell.Name}.{critProt}";

				// could these crit / sneak attack?
				if (Spell.Category == SpellCategory.StaminaLowering || Spell.Category == SpellCategory.ManaLowering)
				{
					var vital = Spell.Category == SpellCategory.StaminaLowering ? "stamina" : "mana";
					attackerMsg = $"With {Spell.Name} you drain {amount} points of {vital} from {target.Name}.";
				}
```

**Comment by jspashett** [comment]
Hmm. Ok. Sometimes they do say Crit as you've seen from my greps. I have been looking for some information on crits, which is hard to come by nowdays.

Note also, that Biting Stike (not critical strike) does give sensible outputs in the log window.

**Comment by gmriggs** [comment]
One issue that is most likely the cause of CS not working for life magic projectiles is in WorldObject_Weapon.GetImbuedSkillType():

```
                case Skill.WarMagic:
                case Skill.VoidMagic:

                    return ImbuedSkillType.Magic;

                default:
                    log.Debug($"WorldObject_Weapon.GetImbuedSkillType({skill?.Skill}): unexpected skill");
                    return ImbuedSkillType.Undef;```

This needs to have Skill.LifeMagic added

It seems like Biting Strike should already be working, which could be confirmed locally by setting PropertyFloat.CriticalFrequency on the wand to something like 0.5

**Comment by gmriggs** [comment]
Also, just to clear up some minor misconceptions that have been floating around in this discussion:

http://acpedia.org/wiki/Announcements_-_2004/07_-_Treaties_in_Stone#Letter_to_the_Players

```Critical Strike for War Magic currently scales from 5% critical hit chance to 25% critical hit chance at maximum effectiveness. In July, the maximum effectiveness will be increased to 50% chance (PvE only).```

This line in the Turbine update notes has mislead a lot of players. It makes it sound like the base crit chance for magic (ie. a wand that doesn't have CS) is 5%, but it is not, it has always been 2%.

http://acpedia.org/wiki/Announcements_-_2002/08_-_Atonement#Letter_to_the_Players

```
                    // Original:
                    // http://acpedia.org/wiki/Announcements_-_2002/08_-_Atonement#Letter_to_the_Players

                    // Critical Strikes: In addition to the skill-based damage bonus, each projectile spell has a 2% chance of causing a critical hit on the target and doing increased damage.
                    // A magical critical hit is similar in some respects to melee critical hits (although the damage calculation is handled differently).
                    // While a melee critical hit automatically does twice the maximum damage of the weapon, a magical critical hit will do an additional half the minimum damage of the spell.
                    // For instance, a magical critical hit from a level 7 spell, which does 110-180 points of damage, would add an additional 55 points of damage to the spell.

                    // Later updated for PvE only:

                    // http://acpedia.org/wiki/Announcements_-_2004/07_-_Treaties_in_Stone#Letter_to_the_Players

                    // Currently when a War Magic spell scores a critical hit, it adds a multiple of the base damage of the spell to a normal damage roll.
                    // Starting in July, War Magic critical hits will instead add a multiple of the maximum damage of the spell.
                    // No more crits that do less damage than non-crits!

                    if (isPVP) // PvP: 50% of the MIN damage added to normal damage roll
                        damageBonus = Spell.MinDamage * 0.5f;
                    else   // PvE: 50% of the MAX damage added to normal damage roll
                        damageBonus = Spell.MaxDamage * 0.5f;
```

This "CS magic starts at 5%" actually comes from the way all Imbue formulas are written. Even more technical, it comes from the way Melee (base 400) and Missile/Magic (base 360) are tied together, some oddities *only* with Missile/Magic CS and none of the other imbues, and the way Turbine changed this formula in the July 2004 update to give a boost for PvE only.

If you have a War Magic skill of 10, and you equip a CS wand, you don't automatically get boosted from 2% to 5% crit chance. For all imbues, you need to reach a minimum skill level threshold before the imbue starts to become effective.

I could go into more detail about this, but a lot of these specifics about CS magic / 5% when it starts to become effective is explained in the code:

```
            // http://acpedia.org/wiki/Announcements_-_2004/07_-_Treaties_in_Stone#Letter_to_the_Players

            // For PvE only:

            // Critical Strike for War Magic currently scales from 5% critical hit chance to 25% critical hit chance at maximum effectiveness.
            // In July, the maximum effectiveness will be increased to 50% chance.

            if (skillType == ImbuedSkillType.Magic && isPvP)
                baseMod *= 0.5f;

            // In the original formula for CS Magic pre-July 2004, (BS - 60) / 1200.0f, the minimum 5% crit rate would have been achieved at BS 120,
            // which is exactly equal to the minimum base skill for CS Missile becoming effective.

            // CS Magic is slightly different from all the other skill/imbue combinations, in that the MinCriticalStrikeMagicMod
            // is different from the defaultMagicCritFrequency (5% vs. 2%)

            // If we simply clamp to min. 5% here, then a player will be getting a +3% bonus from from base skill 0-90 in PvE,
            // and base skill 0-120 in PvP

            // This code is checking if the player has reached the skill threshold for receiving the 5% bonus
            // (base skill 90 in PvE, base skill 120 in PvP)
```

**Comment by jspashett** [comment]
Yes, it's complicated. I remember there being complications... Where does this leave life magic and CS then at this juncture? Right now, quest wands with biting strike do give about 33% crits on life magic, so either that's a bug, or it's correct. CS wands don't seem to do anything much for life magic. I might try asking srand about it, but I don't know if I will get an answer. I do remember reading a turbine forum post where someone asked this, and I remember testing it on retail soon after, but I can't find this on the way back machine, so... well...

**Comment by gmriggs** [comment]
I will fix this up. I think the only bug you are seeing is with CS and Life Projectiles, which the fix is posted in https://github.com/ACEmulator/ACE/issues/2507#issuecomment-565639236 for.

I will be testing all of these scenarios (including Life Projectiles + Bitiing Strike) to make sure this is all working properly

**Comment by jspashett** [comment]
Thanks @gmriggs for putting that change in. I didn't get around to working it out myself. Hopefully that commit can land. As you are aware I am keen on Martyr mage templates, but only me and my dog plays them. I don't really want to steam roller anyone into changing things around, the info on life magic is hard to come by now. My plan with this ticket was to fix it myself, and then continue on to make other contributions to ACEmulator, so hopefully I can try and do that.
