### ISSUE TITLE
Critters dropping Pyreal

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#2755]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```
In the early years of the game critters use to drop pyreal, I believe that was turned off later in the game.
### Repro steps.
none
### The log given by the failure.
none
### Desired functionality.
To be able to turn this feature on/off

What is the use case?
-->

**Comment by LtRipley36706** [comment]
retail loot resolved this issue

**Comment by gmriggs** [comment]
Monsters dropped pyreals @ eor
