### ISSUE TITLE
Object streaming Issue

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#287]
We need to key it off of more than just movement keys...

Example: @telepoi Holtburg
objects should already be there when you come out of portal, but don't appear until after you rematerialize.

**Comment by Forbiddenz** [comment]
I am working on improving this, right now nothing happens until the player is added to a landblock.
At that time the landblock is loaded.

Portal space is not acting as a real loading screen.

Future state will be to load the landblock and all the others around you on portal log in.

Also the system will do the same thing as you run across the world.

This will greatly improve streaming.

**Comment by LtRipley36706** [comment]
Any progress on this issue @Forbiddenz ?

**Comment by Forbiddenz** [comment]
Na not had a ton of time :/. Just got a few hours here and there lately :/

Playing with inventory, will revisit in a little bit

**Comment by spazmodica** [comment]
Doesn’t seem a lot of action on this one.  Quick item: while at Microsoft in a q&a with turbine we found they kept town land locks loaded at all times but ace currently does not.  Is that worth doing to help some of this?   I think this can also be resolved by reordering the tp process to put a layer in portal space load land lock if needs then update position.

**Comment by Forbiddenz** [comment]
If you load all the landblocks at one time when you would be loading a ton of data in ace.   Our landblock load often loads all the wo attached to a landblock so it depends on what your definition of landblock loaded is.

There a admin function in ace I wrote some time ago that can load all the landblocks but it takes a while

There a surly better ways to handle landblocks but I not had much time to investigate much.   Much of this work needs redone once landblock formats aren't understood more and implemented

**Comment by Forbiddenz** [comment]
Dumb phone can't edit.

But this should be more based on landblocks and cells not distance.

Ace needs a function to loans by landblock cell.    I.e. Get all cells around player load cells. 

Anyways back to daddy duty.

**Comment by LtRipley36706** [comment]
Mostly resolved in master... Closing for now
