### ISSUE TITLE
mansion_min_rank = 0 does not work with players not in allegiances

### ISSUE THREAD

**Issue by imamastermind** [ACEmulator/ACE#2906]
Setting mansion_min_rank to 0 seems to mean that all players should be eligible to buy/maintain mansions.  However, if a player has no patron or vassals (and would consequently have an allegiance rank of zero), HasRequirements() returns false because it requires player.Allegiance != null.

https://github.com/ACEmulator/ACE/blob/75fc1ce23cd9d28bb3b1df844e025e676a820587/Source/ACE.Server/WorldObjects/SlumLord.cs#L161

https://github.com/ACEmulator/ACE/blob/75fc1ce23cd9d28bb3b1df844e025e676a820587/Source/ACE.Server/Managers/HouseManager.cs#L590

It looks like these code paths need to be updated for allegianceMinLevel <= 0 && player.Allegiance == null.

**Comment by harliq** [comment]
Rank can't be 0, everyone starts as rank 1.

**Comment by fartwhif** [comment]
http://gallery.esfbc.com/albums/userpics/10001/Capture.PNG

**Comment by imamastermind** [comment]
I think this behavior is correct- the original AC manual has a screenshot of the allegiance tab of a character without any patron or vassals showing a zero rank.  If I recall correctly, the idea is that you have a rank of '1' just for being a part of an allegiance but 0 when you start out without a patron or vassals.

In any case, this issue is mainly about the correct evaluation of allegianceMinLevel for HasRequirements()'s return value when a character's 'allegiance' field is null.
