### ISSUE TITLE
Grievver Caves has no spawns.

### ISSUE THREAD

**Issue by Papsen** [ACEmulator/ACE#2978]
Suddenly Grievver Caves has no spawns (monsters) on my server. The spawn used to be fine before. I have no clue where to look for the problem, or how to solve it. I use World database 0.9.163 and code change log has a latest entry of 2020-03-02.

Can someone help me, and point me in the right direction? Please DO NOT advice me to ask on Discord, because I CANNOT use Discord. I can communicate on GitHub though.

**Comment by LtRipley36706** [comment]
ACEmulator/ACE-World-16PY-Patches#423 resolves this issue

**Comment by LtRipley36706** [comment]
Fixed in database release v0.9.170
