### ISSUE TITLE
Den's of Antiquity issue

### ISSUE THREAD

**Issue by MagiMaster10** [ACEmulator/ACE#3064]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
-  [x] feature request
```

### Repro steps.

When giving the casino gamesmasters their appropriate tokens, the loot that's dropping doesn't match what is listed as current on any of the wiki's. There are no tokens, keys, exp gems, dolls, etc. There are minor trophy's but that's it. It seems like the casinos are running on an older update than they are supposed to. It did some research and it seems like it's running the "Discoveries" version of the casinos rather than the "Cloak of Darkness"/"Risks and Rewards" verions.

### Mention any other details that might be useful.

If I am missing world files I apologize. I am running my own personal server with databases built from ACE-Master and the ACE-World files. I am currently using the latest of both. If the current version of the emulator simply doesn't have the updated versions of the casinos due to the associated content not being relevant or currently implemented then I'd appreciate a simple confirmation that this is or is not the case. Thank you for your patience and understanding.

**Comment by ziang4891** [comment]
There is still a lot to update, casinos being one of the pieces.  It will probably be a while before there is a lot of movement to update the rewards.  ACE-Patches is nominally sitting at 2006-01-Reprisals for most completeness.  There is a long way to go and not a lot of informed contributors

**Comment by MagiMaster10** [comment]
Thank you for the update. Out of curiosity how would one contribute to helping to update missing content or rolling out new content? I'm not sure what kind of experience is require or what kind of time I have, but I am definitely interested in helping if it's possible. Thank you for the help.


-----Original Message-----
