### ISSUE TITLE
Trading issue

### ISSUE THREAD

**Issue by Starcrusher55** [ACEmulator/ACE#3113]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Initiate a trade that will give items from an overencumbered character to one that has no burden.  Error message indicates the overencumbered character cannot complete the trade even though the trade would not give him any burden bac, only take away

**Comment by LtRipley36706** [comment]
fixed in master
