### ISSUE TITLE
public Position(float northSouth, float eastWest) is not accurate

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#3163]
The content team has many positions recorded in dereth n/s coordinates. This data was collected mostly via decal plugins.

An example of such coordinates would be:
Creeping Blight Banner of the Courtyard,37,-114360303,97.53333333333333,-64.26666666666667
which would reside at:
@teleloc 0xF92F0011 [68.000000 20.000000 148.000000] 1.000000 0.000000 0.000000 0.000000

However, if you 
/tele 64.26666666666667s,97.53333333333333e
you end up at:
Your location is: 0xF92F0127 [60.000000 12.000000 148.004990] 1.000000 0.000000 0.000000 0.000000

Another example:
Celestial Hand Buffing Array,37,-114360294,97.58556458155314,-64.22536833286286
which would reside at:
@teleloc 0xF92F001A [80.535500 29.911600 148.000000] 1.000000 0.000000 0.000000 0.000000

however, if you
/tele 64.22536833286286s,97.58556458155314e
you end up at:
Your location is: 0xF92F0127 [60.000000 12.000000 148.004990] 1.000000 0.000000 0.000000 0.000000

In Position.cs, ctor at line 257, we'd like to use this function to convert dereth cardinal coordinates to loc data.

I spent some time on this function but was unable to get it to work without a major rewrite, and, i don't understand how ACE landcell data is stored in the landblock object.

Some tests you might want to do as well:
/tele 0n,0e
/tele 0.5n,0.5e

You may also want to consider taking in doubles for this function instead of floats.

**Comment by gmriggs** [comment]
I think this function might be from acclient, I will have to double check, as it's one of the older ACE functions that someone added very early on

IIRC, the NSWE compass coordinates only have accuracy down to 1 landblock, with the in-game precision of 1 decimal point. If we want to have more than 1 decimal point of precision, this function might need to be modified from the way acclient handles it

**Comment by gmriggs** [comment]
Measuring in game, it looks like each .1 equates to 1 outdoor landcell / 24 meters

So with 1 decimal point, there should be cell-level precision
