### ISSUE TITLE
Cooking: Flour + Nanners recipe does not work

### ISSUE THREAD

**Issue by jsprenkle** [ACEmulator/ACE#3274]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Use flour on Nanners (from Tuskers) ->  Error message: Cannot be used

### Desired functionality.
What would like to see implemented?  Create Nanner Dough
What is the use case?      Cooking.

Wiki shows the recipe. Dunno if it changed.

**Comment by ziang4891** [comment]
The wiki is wrong.  The recipe to make nanner dough requires using dough on nanners, not flour.

**Comment by jsprenkle** [comment]
Accepted wiki being incorrect as resolution
