### ISSUE TITLE
Banished Mu-miyah not counting towards Banished Creature Kill Task

### ISSUE THREAD

**Issue by Delubear** [ACEmulator/ACE#3468]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

1. Start the quest: https://asheron.fandom.com/wiki/Banished_Creature_Kill_Task Banished Creature Kill Task
2. Kill a Banished Mu-miyah
3. It does not count towards the kill task quest

### Desired functionality.

Killing a Banished Mu-miyah should count towards the quest.

**Comment by LtRipley36706** [comment]
will be fixed in 215 db release
