### ISSUE TITLE
Lunuum's Disappearance | Andrilos bugged

### ISSUE THREAD

**Issue by gawainXX** [ACEmulator/ACE#3471]
The NPC mob Andrilos in Lunuum's Disappearance does not respond when you show him the sketch or attempt to talk to him.

You get a message "You allow Andrilos to examine your Sketch of a Viamontian." When you show him the sketch but no follow-up.

Attempted to reset him by killing to no avail.

**Comment by ziang4891** [comment]
You have something wrong, then, as he is setup to respond when shown the Sketch of a Viamontian (32591)

**Comment by ziang4891** [comment]
Another note, repos is not for content

**Comment by gawainXX** [comment]
I will be running that quest again in the next week or so on another character of mine and will get some more details then as well as get the item properties of the sketch I hand him.   

I'm also planning to test whether it does the flag but he just doesn't reply in @tell for whatever reason.

**Comment by ziang4891** [comment]
If you look at the file from master, there are only two possible outcomes from showing him the sketch, but of which have a reply from the NPC

**Comment by gawainXX** [comment]
If I happen to run into the same problem again,  is there any sort of debugging information in addition to chat logs and item properties of the sketch which I could help by providing?
