### ISSUE TITLE
Accessing Objects Between Landblocks

### ISSUE THREAD

**Issue by ddevec** [ACEmulator/ACE#348]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

There is a corner-case atomicity violation within our Landblock system around the observation of transferring objects between Landblocks.

The best **example** I've found explaining the problem:

Note, I've often heard this problem described as "Ships Passing in the Night" if your looking for a shorthand to describe it.

Character Foo observes object Bar moving between two Landblocks.  Foo is on Landblock A, Bar is moving from B to C (so Foo is basically at the corner of a Landblock).  If Foo were to need to interact with Bar (e.g. IdentifyObject from Foo's client, with Bar's Guid as the argument), the Landblock system would have to fetch the Bar WorldObject off of the appropriate Landblock.

Unfortunately, our current design has no way of doing so reliably.  If Bar is in the act of transferring between two Landblocks, it may either be on A or B (or in our current system on neither).  Our only current recourse is to scan all adjacent Landblocks when searching by Guid.  If Bar is in the act of transferring when this scan happens we can miss it with this set of events:

Bar is on A.
We scan B for Bar.
Bar transfers from A to B
We scan A, never finding Bar.

The fundamental issue here is that the scanning of Landblocks is not atomic with respect to the transfer of objects between Landblocks and is additionally not atomic with executing an object's action on that Landblock.  Essentially we need an underlying system that allows us to find an object in nearby Landblocks by Guid, _and_ execute some action on that Landblock atomically.

There are several **possible solutions** to this problem:

**First** - adapting our current design:
Unfortunately, adapting our current design is not likely practical.  Landblocks operate asynchronously, so any operations which query adjacent landblocks for Guids would have to lock _all_ adjacent Landblocks during query (Landblocks would also have to be locked when updating object positions internally).  This will lead to high amounts of locking, and possible deadlock within the system (it is possible, but will be a very treacherous endeavor to create a non-deadlocking Landblock locking ordering).  Overall this design will be inefficient and error prone.

**Second** - Object Directories
The classic solution to this problem is to use an object directory.  We create a directory system (Dictionary with locks) which is essentially a mapping of Guid to current Landblock.  The directory system provides a key-value mapping from Guid to WorldObject, allowing safe lookup of an Object from its Guid to Landblock (this requires atomically updating the dictionary on any landblock transfer -- probably a global lock).  However, there are still other problems with this.  Once we have gotten the Landblock location of the object we must send our event (E.g. IdentifyObject) to _that_ Landblock to safely query the object.  This event send must happen atomically with respect to the directory lookup, _and_ guarantee that the event is run _before_ the object is transferred between Landblocks, otherwise the object may move between querying the dictionary and executing the event to the Landblock, recreating our original problem!

**Third** - Object Directories with Object Work Queues
Instead of having the Landblock perform all object updates, we can associate work with WorldObject.  This allows the work to travel with the object, so it is sufficient to have an object lookup directory.

**Fourth** - Reduction in landblock parallelism
This entire problem stems from the fact that each Landblock can move objects concurrently.  If we guaranteed that only one landblock moved objects at a time (e.g. running all of our landblock update loops sequentially instead of in parallel) that would resolve this issue.

Perhaps this is also a good time to revisit where we have asynchrony in the system, why its needed, and if we should in fact have it?

**Comment by Mogwai-TheFurry** [comment]
I'm most inclined to do option 4 with a single dedicated thread in the LandblockManager that just iterates all the landblocks.

Also, though, dungeons - they don't interact with adjacencies and could have their own threads without worrying about these adjacency issues.

**Comment by ddevec** [comment]
The goal of my core restructure commit was to manage this.  I believe it is now managed.
