### ISSUE TITLE
Rynthid Tentacle Bow (id: 51988) is not typed as a missile weapon.

### ISSUE THREAD

**Issue by BRhodes** [ACEmulator/ACE#3509]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Acquire any Rynthid Bow

### The log given by the failure.

No log, just a weird calculation issue occurs in DamageEvent.GetBaseDamage(Player attacker)

### Desired functionality.

Rynthid Tentacle Bow has type of Missile Weapon.

### Mention any other details that might be useful.

The query below should pull back all missile weapons that aren't correctly marked as such in the weenie DB. There appears to only be 1. On sever side, the typing on the bow as a generic object causes neither the DamageBonus or the ElementalDamageBonus to apply when dealing damage.

select * from weenie as w
join weenie_properties_float as wf
	on wf.object_id = w.class_id
	and wf.type = 63 // 63 is Damage mod, so *should pull back all missile weapons that are worth their salt
where w.type != 3 // 3 is missile weapons, this ones are already labeled appropriately!
and wf.value != 1; // Check to see if the damage mod isn't 1, a lot of odd weapons have a damage mod of 1 for some reason.

**Comment by ziang4891** [comment]
This is correct.  The Rynthid weapons do not get mastery, which is tied to WeaponType, just like the Atlan and Isparian weapons.  Not a bug

**Comment by ziang4891** [comment]
They do not have a WeaponType field

**Comment by ziang4891** [comment]
The WeenieType is not correct...

**Comment by LtRipley36706** [comment]
fixed
