### ISSUE TITLE
When players in inside the Rynthid Access Dungeon, the whole server seems to lag.

### ISSUE THREAD

**Issue by VokardIX** [ACEmulator/ACE#3600]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting 
- [ ] feature request
```

### Mention any other details that might be useful.

When doing the "Seed of Power" quest, when entering the final dungeon (Rynthid Access Dungeon)
Players in the dungeon and outside the dungeon experience a noticeable lag.  
This is seen by not being able to run smoothly.  Not being able to go into or out of combat stance.
Not able to see when spells are cast, or when you recall out of the dungeon.

Server was rebooted and this same behavior was experienced again.  

When you portal out of the dungeon, all players go back to normal behavior.  No lag, no delays.  
A player goes back in the dungeon, and immediate lag happens again.

Dungeon is  Rynthid Crystal Access Device at 63.1S, 65.5W.

Walk through of the quest can be found here: http://acpedia.org/wiki/Seed_of_Power

First 3 dungeons did not have any issue.  Just the final one.

Thanks for all you do.

**Comment by LtRipley36706** [comment]
I believe this has been resolved. re-open if that is incorrect
