### ISSUE TITLE
Character Vanished

### ISSUE THREAD

**Issue by FireCulex** [ACEmulator/ACE#3605]
### Bug Report 

Logged in to find brothers character had vanished. Level 17 Created 7/3/21, today is 7/6/21 No longer a vassal/follower of my character.  Name has disappeared from friends list but it says offline. https://i.imgur.com/fwjnaZH.png
Name was UpperDecker

### Repro steps.
Unknown

### Desired functionality.

What would like to see implemented? Characters not disappearing.

**Comment by gmriggs** [comment]
Which server is this on?

You would have to report this to the server you are playing on.

**Comment by FireCulex** [comment]
Thanks. It was Coldeve, I've joined their discord and hopefully someone will look into it.
