### ISSUE TITLE
Weather Command

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#3674]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
```

### Desired functionality.
The ability to start and stop the Weather on command:
/setweather rain 
/setweather snow 
/setweather clear
Something like that.

**Comment by gmriggs** [comment]
I think this is a client-side effect based on the server time.

This would require adjusting the server time / booting everyone from the server. It would also require reversing the prng function on the client that controls the weather.

**Comment by LtRipley36706** [comment]
Not possible.
