### ISSUE TITLE
Castle of Lord Mhoire Quest can't be done.  Thought it was live.  Last update says it is.

### ISSUE THREAD

**Issue by VokardIX** [ACEmulator/ACE#3676]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

The Castle of Lord Mhoire Quest starts out fine.  Get the Strange Jewel when using the Ancient stones.  
Lord Hendrel spawns.  No issue
Lord Trimere spawns.   No issue
Lady Saliane will not spawn.  Have tried every conceivable area in and around 65.0S 44.2W.  Day time, night time.  As far as .5 clicks away to exactly on the spot.  Will not spawn.
No Gargoyle at 64.6S 44.1W.  So even if Lady Saliane did spawn, no place to hand in candles.

 Check with server admin.  
 Server Binaries version 1.31.4049.20210912183801-master-cf13e04 - compiled Sun Sep 12 18:38:01 2021 : ACEmulator
 Server database version Base: v0.7.18 Patch: v09.229 - compiled Sun Sep 12 18:45:48 2021
 Server is compiled in RELEASE mode
 
 Verified system had been rebooted.  Twice.
### Mention any other details that might be useful.
Other quests listed are now active.  IE Bonecrunch worked great.  Will wait to hear from y'all.

Thanks for all you guys do.  It's greatly appreciated.  Keep up the great work.

**Comment by llupin** [comment]
I am running 1.31.4061 on a private server. I just complete this quest with no issues.

**Comment by VokardIX** [comment]
Then there must be something else missing from the server that I'm playing
on.

It's not my server (don't have one).

While he's on that build of the database, there's definitely something
missing.  Can't get the last candle, and there isn't a gargoyle there to
hand them to anyway.

Server address is wuck.ddns.net:9080.  Not sure if you can check to see
what the admin has missing or not correct.

Or even if you'd want to.

Thanks for the confirmation.

Regards,

Michael Voelkering

**Comment by VokardIX** [comment]
Wait a minute..

How are you on build 1.31.4061?

From https://github.com/ACEmulator/ACE current release is 1.31.4049.
[image: image.png]

You're on a newer build.

Where do I tell the admin to get 1.31.4061?

Regards,

MV

**Comment by llupin** [comment]
Its the current version. I downloaded and compiled it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by VokardIX** [comment]
So, even though the page shows .4049, it's really .4061?

Okay...

Can you send me the link to that page?

**Comment by VokardIX** [comment]
Admin went and downloaded again.  Only able to download the .4049 version.
No idea where to get the .4061 version you have.  Please send where this
can be downloaded from.

**Comment by VokardIX** [comment]
I assume it's not a public release.

Anyway, thanks for all you guys do.  I know this is out of your free time.

mv

**Comment by llupin** [comment]
https://github.com/ACEmulator/ACE

click on the green button “code” and select “download zip”.

**Comment by VokardIX** [comment]
All I get it the download for ACE-1.31.4049.zip

There isn't one for 1.31.4061.  No idea where you're getting it.
I assume you have access to something the public doesn't have access to.
[image: image.png]

Regards,

mv

**Comment by llupin** [comment]
[A screenshot of a computer  Description automatically generated with medium confidence]

**Comment by VokardIX** [comment]
I may have figured out where you're getting it from.

Is the file called ACE-master.zip?

Regards,

mv

**Comment by llupin** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by VokardIX** [comment]
First, thanks for the help.

Second, the server admin isn't wanting to compile it himself.

He's going to wait until that is the official release.  Unless you know
where he can get it already compiled, to install.  He's running it on a
windows box.

Regards,

mv

**Comment by VokardIX** [comment]
Seems this issue will be resolved in the next release of the verified server release.  Dev can get this working by compiling the 1.31.4061 build.  And while admins can do the same, it's not a current release that is pre-compiled for download, such as what is listed in the ACEmulator Core Server area where admins of their separate systems usually go to get the latest verified versions.

**Comment by LtRipley36706** [comment]
Close this as it seems to be resolve, reopen if not

**Comment by VokardIX** [comment]
It should be resolved now that the release version has been updated to 4086.

Regards,

MV

**Comment by VokardIX** [comment]
I know you guys closed this, but it's still not working for the server I'm
on.

Seems just this one area of the Graveyard isn't getting updated.  I know
that sounds really strange, but it is.  I'm attaching two screenshots.  My
location is shown along with the coords.  You can see that the gargoyles
are not where they should be.

The odd thing is, I have Lord Hedrel's Brand, and Lord Trimere's Brand,
which should mean the quest is live, but Lady Saliane
<http://acpedia.org/wiki/Lady_Saliane> will not spawn anywhere.  From the
screen shot you'll see I'm very near 65.0S 44.2W .  I've used the jewel in
and around that area over 100 times.  Even if she did, where do I turn in
the 3 brands?

Is there any way to reset that area of the graveyard?

Unfortunately, this isn't my server, so I don't have rights to do anything
on it.

It's currently updated to the latest releases for both the server release
and the database release.
Server v1.33.4105 and database v0.9.237

I am in contact with the guy that is running the server, and he says he's
reloaded things.  Not sure what else to do.

Any suggestions on why it might be doing this or what action can be done?

Thanks.

MV
