### ISSUE TITLE
Black Spear Spells Apply When they Shouldn't

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#3688]
### Repro steps.
* Create WCID 33718 and hook on a Yard Hook at a home.
* Use the Black Spear of Mukkir Strength.
* (Alternatively, `/addspell 3985` and cast it upon yourself)

* Equip a weapon with a Defender Cantrip (e.g. `/additemspell 6091` to add Legendary Defender to the weapon)

* Appraise the item, and you will see it has +13% extra Bonus to Melee Defense (9 from Legendary Defender, 4 from Mukkir Sense). 
* These two spells are in the same spell group and should be applied together (result should be only +9% from the higher level Legendary Defender spell on the weapon).

This is not just a cosmetic issue on the appraisal of the weapon, as your effective Defense skill is increased by +13% as well.

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/3690
