### ISSUE TITLE
Training Staff (Weenie:45550) coded as Heavy Weapon instead of Light

### ISSUE THREAD

**Issue by Spentfire** [ACEmulator/ACE#3712]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create Gharu'ndim Character specialized in Light Weapons, but when entering the game, only given an IOU
Using Admin level @create 45550 creates a training staff with Skill: Heavy Weapons

### Desired functionality.
Will try to fix myself by editing the weenie, but perhaps these are two separate issues...

**Comment by ziang4891** [comment]
You have something wrong with your DB, as 45550 is a light weapon staff

**Comment by ziang4891** [comment]
One thing to note, this issue is with the Patches content, not a server issue

**Comment by ziang4891** [comment]
Fixed in https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1116

**Comment by Spentifre** [comment]
Absolutely true ziang4891.  First noticed it on Coldeve.  Wow, you guys are fast!
