### ISSUE TITLE
not sure how to fix this

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#3742]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Cant really repo this, it happens only once in awhile. Ill go into an area or recall to the lifestone and it acts like its a new ( unexplored ) area and wants to download it. the the blue progress line appears for a few seconds then disappears but leaves the boarder. I have logged out and back in, tried a full new install, nothing works. Please help! I know this is not the place to post this but I cant remember my login for Discard and I cant post as a Guest. Thanks!

### Mention any other details that might be useful.
Im not sure how to fix this, I have had this happen to 4 Character over 3 servers. ColdEve, ThistelCrown and now IsparAC. I cant seem to find a command or anything that can help me. I have the most up to date cell, Portal and client that has been indicated to use. not sure what to do. 
![Capture1](https://user-images.githubusercontent.com/38050842/142396617-57bdc3b0-f096-47ec-9f60-78020edaf457.JPG)
![Capture](https://user-images.githubusercontent.com/38050842/142396630-7a9c2b69-b0a0-47a1-909c-d5e8f5a47d37.JPG)

**Comment by gmriggs** [comment]
have you tried jumping?

**Comment by Warloxx01** [comment]
Um... OMG are you kidding me. No I didnt but... Maybe I should have. (Warloxx feel like a COMPLETE idiot! ) Thank you gmriggs!!!!

**Comment by gmriggs** [comment]
The jump bar and the download bar are the same UI element. I'm not sure why the download bar would be appearing when you walk through a portal, or why it would be staying on the screen, but jumping has indeed been known to get rid of it afterwards
