### ISSUE TITLE
Abandoned Armory dungeon missing first two pressure plates.

### ISSUE THREAD

**Issue by Delubear** [ACEmulator/ACE#3764]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Go to the Abandoned Armory as part of the Sanguinary Aegis quest.  The first two "small rooms" that should contain a pressure plate to open the door to the next area, don't have a pressure plate.  This leaves you unable to complete the dungeon.  The third pressure plate did appear to be working however.  Had to get an admin account to /delete the 2 doors with issue.

### Desired functionality.

Ability to complete quest without admin intervention.

### Mention any other details that might be useful.

We cleared all enemies and ran around a bunch where the plate should have been without luck.  Followed this guide: https://asheron.fandom.com/wiki/Sanguinary_Aegis_Quest

**Comment by LtRipley36706** [comment]
Unable to reproduce issue on stock content servers. All plates accounted for and doors able to be triggered, quest can be completed without intervention
