### ISSUE TITLE
Ice Badge is missing attuned/bonded properties

### ISSUE THREAD

**Issue by Delubear** [ACEmulator/ACE#3773]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Ended up doing the quest [Snowman Village](https://asheron.fandom.com/wiki/Snowman_Village) and turning in the reward to [The Mayor](https://asheron.fandom.com/wiki/The_Mayor).  Got the [Ice Badge](https://asheron.fandom.com/wiki/Ice_Badge) award, and it has the Ivoryable property but I was unable to apply ivory to it as it is missing the attuned and bonded properties.

### Desired functionality.

Should have attuned and bonded properties as listed in the wiki.

**Comment by sLackeR-hub** [comment]
It seems as though that may be a turbine error as it was pcapd that way, I could be wrong though.

[https://github.com/ACEmulator/ACE-PCAP-Dynamics-Exports/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Generic/Jewelry/25787%20Ice%20Badge.sql](url)
