### ISSUE TITLE
Dire Champion Tokens not sharing experience in fellowship

### ISSUE THREAD

**Issue by Cyprias** [ACEmulator/ACE#3836]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Get a Dire Champion Token    
Join a fellowship with someone else.  
Turn in token  
Check if fellowship partner received experience. 

### Desired functionality.
Split the exp with other players in the fellowship.

### Mention any other details that might be useful.
[Wiki](http://acpedia.org/wiki/Dire_Champion_Token) page mentions the exp being shared. I used to farm these on retail to quickly push fresh 50s to higher level.

**Comment by brycter** [comment]
in retail for these tokens there was no distance limit for xp sharing
