### ISSUE TITLE
Abyssal Olthoi Chasm exit portal is not spawning at the bottom of the chasm.

### ISSUE THREAD

**Issue by Hermit-Lord** [ACEmulator/ACE#3950]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Ascend to bottom of the Abyssal Olthoi Chasm to find that the exit portal is not spawning

### The log given by the failure.
 Normally this include a stack trace and some other information about the failure. 

### Desired functionality.

It would be nice to have the exit portal at the bottom of the Abyssal Olthoi Chasm so that you can leave the dungeon, like what you could do during retail.

**Comment by Hermit-Lord** [comment]
![Olthoi Chasm exit portal](https://user-images.githubusercontent.com/122661571/212457310-e8fd8ec7-2ee0-4106-a0ed-d2c028105421.JPG)

**Comment by lugielord** [comment]
According to vloc data, Surface Portal - @teleloc 0x5D4E0113 [75.250000 -40.819336 -54] 1 0 0. 0.
Also world objects data confirms 38239	14	5D4E0113	-27.24	-39.72	-0.23	Surface Portal	Surface Portal (0.7N, 44.7E).
Looking at weenies, I see ace46019-surfaceportal	Surface Portal matches this data.

**Comment by lugielord** [comment]
Since this file only existed in 'Core' previously, I copied the whole .sql file into 'Patches' in order to make the one addition.  Hope that is the correct procedure for changes such as this.

**Comment by Hermit-Lord** [comment]
The portal is there, yes. I can manually spawn it. It did take me awhile to figure out what the weenie ID was. 
It just wasn't doing it on it's own it would seem. At least on my own private ACE server. I have not done anything to my server besides the base setup per instructions.

**Comment by lugielord** [comment]
![abyssal-olthoi](https://github.com/ACEmulator/ACE/assets/156704507/08102c46-c973-4455-a47b-35e563c0ac78)

**Comment by lugielord** [comment]
I've checked in a change to the database project, so next db build will add the Surface portal permanently.
