### ISSUE TITLE
Vendor Product List - Not Visible 100% Visible at Bottom of Window

### ISSUE THREAD

**Issue by KevGenJr** [ACEmulator/ACE#3956]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

1. Vendor bar located at very bottom of screen. 
2. Vendor with more than 4 product lists
3. When the vendor bar is in this location the user cannot select the bottom most option from the list of products.

### Desired functionality.

1. I would like the list to show in any case. 
![VendorList](https://user-images.githubusercontent.com/90426958/220916525-7f3a87fd-c1c4-45c9-84ab-66d57153f3cb.png)

**Comment by gmriggs** [comment]
this is an acclient ui issue. there is nothing a server emulator can do about this.

**Comment by KevGenJr** [comment]
@gmriggs - Is there a DM feature here? I would like a little chat if possible as emulators are a new thing to me and I feel I could really help if some explanation is provided. :-)
