### ISSUE TITLE
Dark Isle - Black Coral - Fail to Merge to inventory

### ISSUE THREAD

**Issue by KevGenJr** [ACEmulator/ACE#3962]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

1. Go to Dark Isle
2. Pick up Black Coral at beach
3. At some point > 1 when you try to pick the Black Coral up
![BlackCoral_Bug](https://user-images.githubusercontent.com/90426958/229133621-c804e523-c40c-43e3-877a-1070d30790bd.png)

### The log given by the failure.

The Black Coral can't be merged
Source stack not found!

### Desired functionality.

If stack is = full, start new stack in inventory. 
NOTE: My inventory bar looks full but I have 4 empty slots at the bottom. 

### Mention any other details that might be useful.

I AM IN THE MIDDLE OF SOCIETY DAILYS, MAYBE SOMETHING TO DO WITH IT? 

If there is an issue with the image, shoot me a PM on Discord: Catastrophie#6212

**Comment by gmriggs** [comment]
The message 'source stack not found' indicates this is a problem with the item laying on the ground, and not the destination stack

My guess would be maybe your client thinks there is an item there, when there really isn't on the server anymore

**Comment by KevGenJr** [comment]
OK. 

Question: I believe someone told me we cannot change any code on the client side? Just the server side? 

Thanks.
