### ISSUE TITLE
Dark Isle - Corrupted Essences 

### ISSUE THREAD

**Issue by KevGenJr** [ACEmulator/ACE#3963]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

1. Go to Dark Isle
2. Give Tyrina of Arwic an Essence (DI Trophie)
3. Receive the following green font message: "You allow Tyrina of Arwic to examine your Lesser Corrupted Essence." 

Gives no reward XP. 

### The log given by the failure.

The Lesser Corrupted Essences can't be given.

### Desired functionality.

Give item = receive xp. 

### Mention any other details that might be useful.

 
![EB6dhSWhH2](https://user-images.githubusercontent.com/90426958/229141592-06f61030-dbce-4f0a-90f5-f3a5aba7c426.png)

**Comment by Boop-AC** [comment]
Fixed in https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/1513
