### ISSUE TITLE
Feruza ibn Salaq is giving out double helpings of the searing disk (7509), and eye of the storm (7514) scrolls

### ISSUE THREAD

**Issue by Fire-Chimp** [ACEmulator/ACE#4103]
Feruza ibn Salaq is giving out double helpings of the searing disk (7509), and eye of the storm (7514) scrolls
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by LtRipley36706** [comment]
no evidence this was ever fixed, retail bug
