### ISSUE TITLE
Subscription data model concept + GLS replacement

### ISSUE THREAD

**Issue by Mogwai-TheFurry** [ACEmulator/ACE#42]
Login == account
retail "AC account" == subscription (under the hood, as Turbine did it)
subscription == a set of characters on worlds

Old/retail paradigm: 1 login for every subscription
New paradigm: 1 master login, select a subscription

This will entail building a set of REST services and a new launcher with Thwargle.

**Comment by Mogwai-AC** [comment]
This is low priority.  Wanted it logged as legit to-do, though.
