### ISSUE TITLE
Add column to authenticationDB.account for access rights

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#44]
Need to add a column for access rights so to allow accounts to be able to create characters with IsAdmin or IsEnvoy bools set.

**Comment by Mogwai-AC** [comment]
Kaos: We just need a simple rank system and /setrank command or similar that flows through. 1=registered, 2=envoy, 3=sentinel, 4=admin, etc... Everyone goes under 1 automatically and an admin can use the /setrank command to give out any additional ranks. Value should be stored in DB.

**Comment by LtRipley36706** [comment]
for reference, values assigned to characters:

SetPropertyBool(PropertyBool.IsPsr, false);
SetPropertyBool(PropertyBool.IsAdmin, true);
SetPropertyBool(PropertyBool.IsArch, false);
SetPropertyBool(PropertyBool.IsSentinel, false);
SetPropertyBool(PropertyBool.IsAdvocate, false);

would think it goes like this:

0=player
1=advocate (isAdvocate)
2=sentinel (isSentinel)
3=envoy (isPSR)
4=developer? (IsArch)
5=admin (isAdmin)

**Comment by Mogwai-AC** [comment]
Had a discussion about this in Discord tonight.  The client sends 2 uints for IsEnvoy and IsAdmin.  Need to clarify if this is 1 field with a bitmask, 1 field with tiered elevation, or multiple fields.
