### ISSUE TITLE
ACE Chat System

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#5]
StackOverflow had something working in chat, perhaps submit a pull request.

**Comment by Forbiddenz** [comment]
Working on it, but going to need a landblock system I think before we can get very far on this..

**Comment by kaos00723** [comment]
From Rawaho: "The chat really needs broadcast support and to do that we need a working grid system and to do that we need to load the dat files
I am working on handling the dat files but haven't had much time the last few days"

**Comment by Mag-nus** [comment]
Local (say), and tell now work.
Fix: The names are not clickable. Not sure why.
Fix: Local (say) is world global for now. It needs a range restriction of some sort.

Need to add joining and using of the chat channels (general, trade, etc...)

**Comment by Mag-nus** [comment]
Fix: Local chat still broadcasts globally
Test/Fix: Chat Channels (General, LFG, ...) are broadcast to everyone. We should probably check if the recipient subscribes to the channel first before sending the message to them.
