### ISSUE TITLE
Saving a Character to the DB

### ISSUE THREAD

**Issue by Mogwai-AC** [ACEmulator/ACE#51]
intermittently?  on logout?  by command?  something

**Comment by Rawaho** [comment]
Should be a combination of the first 2, we can't just have only on logout, if a player is in a long play session and the server crashes for whatever reason it would be a massive rollback.

**Comment by LtRipley36706** [comment]
Old school AC showed a message each time a character was saved.

"[charactername] has been saved."

it was probably on a 5 or 10 minute interval. They later just hid the message.

**Comment by spikeone83** [comment]
best is to save characters routinely, characters not saving often server side is one of the easy ways of duping in any online game

**Comment by fantoms** [comment]
A small portion of saving the character is available in Pull Request #125, as it will save the character properties to the database.

**Comment by LtRipley36706** [comment]
Saving intermittently and on logout is in.
