### ISSUE TITLE
Switch from log4net to LoggerFactory

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#578]
A suggestion from Rawaho.

Reference: https://stackify.com/net-core-loggerfactory-use-correctly/

**Comment by Hentaya** [comment]
So the conclusion from that article is: My suggestion: Just keep doing
logging how you always have.

After all the time I have spent messing with the new
Microsoft.Extensions.Logging API, I would ... not even worrying about the
new LoggerFactory.

**Comment by LtRipley36706** [comment]
Closing this, seems unneeded.
