### ISSUE TITLE
Client does not send GameActionLoginComplete after Entering World

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#663]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

This does not happen with specifically reproducible steps for me but the sequence is to start the server and then connect with the client and enter world with a character. It will be apparent the issue is occurring if while portalling into the world you do not receive vital stats for Health/Stamina/Mana, other times vitals do send but you do not exit the purple bubble state.
### The log given by the failure.

The client no longer processes most messages it receives, sends nothing further outbound and network times out after about 2 minutes.
### Desired functionality.

After character enters world and exits portal it sends GameActionLoginComplete 100% of the time,
### Mention any other details that might be useful.

I suspect this issue is due to not fully handling the optional headers correctly in NetworkSession or something along those lines. Obviously the client is expecting something in either a certain order or a certain packet sequence is not being returned because the sending of the GameActionLoginComplete message is entirely automated from the client side and seemingly not triggered by a specific incoming event/message

**Comment by gmriggs** [comment]
This bug has been fixed for quite some time now
