### ISSUE TITLE
World object movement / animation needs proper implementing

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#7]
Per Rawaho

**Comment by Forbiddenz** [comment]
It's not just world object movement but it's the entire world object.  It needs implemented correctly before any major feature can be added or else the rework will be awful.  The current world object needs uncoupled and it should be broken down into multiple sub objects to handle the correct sub object layers like sub models etc .  If dive right it could be combined with database tables to generate objects correctly based on sql table data

**Comment by LtRipley36706** [comment]
Animation is in.. Still needs multiplayer handling to cover movement
