### ISSUE TITLE
Single cast Double damage/Attack

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#780]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

I did /grantxp 1***** took him to lvl 241 made all his magic skills/stats 100 (no buff at all) used a lvl 1 fireball and started killing a silver tusker as i did i noticed 2 hits. so i looked closer and found it hit right away then 5 seconds later hit again even though i didnt cast a second time. Also its not a repeat of the same cast it a completely seprate cast. one will hit then the next will be resisted or has a different damage amount. on a side note my mana never dropped while cast either. Have a screenshot but unsure how to attach it.
### Mention any other details that might be useful.

did this all as a Admin.

**Comment by gmriggs** [comment]
This issue has been fixed in https://github.com/ACEmulator/ACE/pull/787

Thanks for the bug report!
