### ISSUE TITLE
Landblocks use a lot of memory

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#784]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

I added a debug command (can't forget what it is specifically) that loads all landblocks.

Right now, on a 32GB machine, it's not possible to load all the landblocks. You'll run out of memory fast.

Some of the data in the landblock physics code is being duplicated often. This should be shared when possible.

Using Visual Studio memory profiler makes it easy to see what objects are the problem.

**Comment by gmriggs** [comment]
Objects loading from DAT should reference a static immutable instance by default.

Only when fields are changed should a new mutable property be created.  See the ModelMesh class for an example

Vertex indices / buffers should also be utilized where appropriate

**Comment by OptimShi** [comment]
For reference, the console command is 

"loadalllandblocks" - Loads all Landblocks. This is VERY crude. Do NOT use it on a live server!!! It will likely crash the server.

**Comment by gmriggs** [comment]
Fixed by https://github.com/ACEmulator/ACE/pull/936
