### ISSUE TITLE
Client Launcher needed

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#8]
We need a client launcher. Perhaps we use a modified thwarglauncher.
https://thwarglauncher.codeplex.com/

For decal to work:
"for emu, you should make a launcher that injects OR a shim client that loads the client and injects"
"just stuff inject.dll in the process space early enough and it will do its thing"

**Comment by Oykib** [comment]
[ACEmuLauncher.zip](https://github.com/ACEmulator/ACE/files/752670/ACEmuLauncher.zip)

**Comment by Oykib** [comment]
[ACEmuLauncher v0.0.0.3 source.zip](https://github.com/ACEmulator/ACE/files/753512/ACEmuLauncher.v0.0.0.3.source.zip)
Latest version that has profiles.

**Comment by damnubber** [comment]
Any specific reason this isn't in the ACE solution?

**Comment by Oykib** [comment]
This can be deleted. I was informed that they do not need a launcher developed and have one in mind already.

**Comment by Mogwai-AC** [comment]
Thwargle has one, hoping to release it today.
