### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#811]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Go to any vendor and try to sell an item ( sword at the blacksmith / wand at the mage shop) you can drop it on the vendor or open the sell window, either way it shows up ready to be sold. but when you hit sell item or sell all it crashes.

**Comment by OptimShi** [comment]
I am currently working on this. Fixed the reported bug, but others presented themselves that I am attempting to solve while I'm knee deep in it.
