### ISSUE TITLE
Inventory Functions Do Not Check for Burden

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#864]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```
### Repro steps.
* Load up character to full 300% burden
* Pick up more items. 

### The log given by the failure.
n/a

### Desired functionality.
* Items should not be added/transferred.
* Should generate WeenieError.YouAreTooEncumbered or WeenieErrorWithString._CannotCarryAnymore

### Mention any other details that might be useful.

Probably easiest to adjust inventory functions and let those handle all errors, as opposed to adding functionality within each system (e.g. Recipes, Loot, etc)

**Comment by Mag-nus** [comment]
Should be fixed in #1197
