### ISSUE TITLE
Stacking Into Containers

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#865]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

* /ci 8327 (Gold Pea)
* /ci 8327 (Gold Pea)
* /ci 136 (Pack)
* Place one Gold Pea into the Pack.
* Place the other Gold Pea into the Pack
Peas stack and are placed into main backpack.

### Desired functionality.
The Gold Peas should be in the Pack, not the main backpack.

**Comment by Mag-nus** [comment]
Should be fixed in #1197
