### ISSUE TITLE
Picking Up Open Container

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#866]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

* /ci 136 (Pack)
* Drop pack into world.
* Open Pack
* Pick up pack without closing.

Packed will be placed into inventory, but is locked. If placed back on ground, user will be unable to open it. Not tested, but I assume you can also pick up a pack while another player is using it. YOINK!

### Desired functionality.

* If player picking up the pack is the one with it open, the pack will remove/set to false the IsOpen flag when picking it up.
* If another player has the pack open, generate error (Perhaps WeenieError.Frozen - "The item is under someone else's control!")

**Comment by mcreedjr** [comment]
These issues have been resolved with the referenced PR.
