### ISSUE TITLE
Database schema oddities

### ISSUE THREAD

**Issue by Mag-nus** [ACEmulator/ACE#884]
WeenieClassId: Are we using int or uint
WeeniePropertiesEmoteAction.WeenieClassId is defined as a (int?)
WeeniePropertiesCreateList.WeenieClassId is defined as a (uint)

Properties that exist in PY16 source but not ACE EF models:
Recipe.Unknown4

**Comment by LtRipley36706** [comment]
@Mag-nus 
Recipe.Unknown4 == salvage_Type in current exports
