### ISSUE TITLE
Landblock Double+ Spawns

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#887]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Load ACE
/telepoi Holtburg
run to Meeting Hall and enter portal
wait inside hall approx. 3 minutes
use exit portal
return to Holtburg to find duplicated spawns

### The log given by the failure.

N/A

### Desired functionality.

NPCs and other objects spawn once, or correctly.

**Comment by gmriggs** [comment]
Fixed by https://github.com/ACEmulator/ACE/pull/929
