### ISSUE TITLE
Rework packet pipe

### ISSUE THREAD

**Issue by Rawaho** [ACEmulator/ACE#9]
Rewrite packet and fragment handling to delay and allow for combining outgoing fragments.

**Comment by Zegeger** [comment]
You can assign this to me

**Comment by kaos00723** [comment]
@Zegeger , issues can only be assigned to the issue starter or a member of the org. You're the only person working on this currently so when you submit the PR just reference issue #9 and it will close automatically after being merged.

**Comment by Mogwai-AC** [comment]
Zegeger's work is now merged.  Closing the issue.
