### ISSUE TITLE
Alter Shard Schema to avoid record caps based on uint32

### ISSUE THREAD

**Issue by LtRipley36706** [ACEmulator/ACE#930]
As of writing in ACE the following tables for characters have a cap of UINT32.MaxValue
```
            CharacterPropertiesContract = new HashSet<CharacterPropertiesContract>();
            CharacterPropertiesFillCompBook = new HashSet<CharacterPropertiesFillCompBook>();
            CharacterPropertiesFriendList = new HashSet<CharacterPropertiesFriendList>();
            CharacterPropertiesQuestRegistry = new HashSet<CharacterPropertiesQuestRegistry>();
            CharacterPropertiesShortcutBar = new HashSet<CharacterPropertiesShortcutBar>();
            CharacterPropertiesSpellBar = new HashSet<CharacterPropertiesSpellBar>();
            CharacterPropertiesTitleBook = new HashSet<CharacterPropertiesTitleBook>();
```

Each of these tables has the following first column
```
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Id of this Property',
```
and that column is the primary key
```
PRIMARY KEY (`id`),
```

A way to avoid that problem, assuming Entity Framework supports it, is to change the primary key to a composite of multiple columns within the table that could be used as a unique record identifier

For example, in contracts table
```
PRIMARY KEY (`character_Id`, `contract_Id`),
``` 

Ideally, any table in shard might want to convert to composite keys but the most critical to start with would be the enchantment registry table as that one as the most churn I believe.

**Comment by LtRipley36706** [comment]
with #1202 and #1213 merged, we'll see how thing progress with the most critical table converted to composite key.

If all goes well, we can re-evaluate other tables next month for conversion

**Comment by Mag-nus** [comment]
ACE.World.Landblock_Instance should have a restriction on guid column to only allow id's in the static guid range 0x7#######

**Comment by LtRipley36706** [comment]
only important IF isLinkChild is false..

the best and only way to enforce that is by using parser tool to output proper guids

**Comment by Mag-nus** [comment]
#2563 completes the remaining major shard AUTO INCREMENT tables.
