### ISSUE TITLE
Melee attack penalty is not accurate for zero stamina

### ISSUE THREAD

**Issue by fdsfsd916** [ACEmulator/ACE#944]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Per discussion with gmriggs, attack penalty for zero stamina is capped at -50.

### The log given by the failure.
None.

### Desired functionality.
What would like to see implemented?

The stamina penalty for melees is a defense penalty only, not attack. This is also true for archers. Like with Melees, the penalty is that the attack is equivalent to what it would be if you set your attack bar all the way to the left. For Archers, they lose accuracy, but no more than they would had they set the bar to the left themselves. They even shoot faster in this state (due to decreased accuracy), I know this to be true because I've done this in retail.

What is the use case?

Accurate Melee and Archer behavior for zero stamina, however edge of a case that may be.

### Mention any other details that might be useful.
My assertion here is that there is no statistical difference in attack success rate for stamina and no stamina for melees. This is supported by my own experience and discussions with other melees on Discord. Zero stamina is a state that I often played in and is a tactic used by many shield-wielding melees. It is a known game mechanic to melees, but unfortunately there is mis-information stemming from a single ACWkiki article that has since migrated to ACPedia and copied by ACWikia. I have played melees since Beta and I know that this to attack penalty for zero stamina was never true, not even in Beta.

Below is objective proof of these scenarios:

Video: https://www.youtube.com/watch?v=CyzfhIgqsiU
Time: 5:59 to 6:22

- 	Fights a Hollow mob.
- 	25 swings/6 misses = 76%  success rate (Stamina)

Time: 6:22 to 6:40

- 	Continues fighting the same mob.
- 	21 swings/8 misses = 61%  success rate (No Stamina)

I will note here that the sample size is small, but this will be clearer by the other videos below. Yes, it is lower for no stamina, but consider the sample size. Overtime, I know that these two states (stamina vs. no stamina) will have no statistical variation. This was confirmed in the ACForums before, but unfortunately we no longer have that resource. 

Video: https://www.youtube.com/watch?v=fwb9fnv71UI
Time: 1:47 to 2:32

- 	Kills 3 Dark Leechs in 60 hits.
- 	60 swings/7 misses = 88.33%  success rate (Stamina)

Time: 4:17 to 4:27 

- 	Kills 1 Dark Leech in 12 hits.
- 	12 swings/2 misses = 83.33%  success rate (No Stamina)

Again, I believe this to be a statistical insignificance given the way AC's combat system works. Yes, it is lower, but again it is within an acceptable range variation for AC's combat system since even a character with stamina will produce the same variation. Later in the video, he attacks a Dark Magus and misses significantly. However, that mob has +50 MeleeD compared to the Dark Leech. I would have included those stats here, but there are no "with stamina" metrics to measure against. To measure them against the Dark Leech stats would not be accurate given the significant difference in MeleeD (Also, note how significant a -50 MeleeD impacts a melees attack success rate).

Video: https://www.youtube.com/watch?v=MUaD53D9c74
Time: 1:20 to 1: 49

- 	Fights a Drudge Skulker.
- 	21 swings/17 misses = 19.04% success rate (Stamina)

Time: 1:49 to: 2:31

- 	Continues fighting the same Drudge Skulker.
- 	32 swings/24 misses = 25% success rate (No stamina)

And finally, this video shows this same variation, but in the opposite direction. If there was an attack penalty for zero stamina of any kind, it would dramatically impact the hit rate for this character since his attack rate was already at 20%. Given the bell curve of ACs combat system, this would have been immediately measurable in the next 32 attacks. However, this user's attack success rate had actually increased. This shows the same statistical variation as the other two videos.

There is no attack penalty for zero stamina. Even as noted as far back as Nov. 2000 in this article: http://mu.ranter.net/asherons-call/aphonouss-melee-vs-mage-comparison "Attacks at full skill but minimum power without stamina." Mu was correct then and it was correct at the end of Jan. 2017. This has been confirmed with players on Discord who have actually played as melees throughout retail and at the end of retail.

I do understand how trustworthy the wikis have been (which has been earned) and believe that they are an excellent resource, but I **know** they are wrong in this case.

**Comment by gmriggs** [comment]
This is some very good evidence to take into consideration.. even though the sample size isn't huge (as mentioned), this thread would be good place to collect any 0-stamina combat videos for reference

The PCAPs would also be a good resource for this, although the search capabilities in aclogview are rather limited currently, and could really use a 'spatial search / querying' feature that takes the full state of the game session into evaluation

**Comment by gmriggs** [comment]
This has been updated: https://github.com/ACEmulator/ACE/pull/1142
